### ISSUE TITLE
Replace links to previous version of R Ecology Lesson

### ISSUE THREAD

**Issue by tobyhodges** [datacarpentry/semester-biology#1035]
### What is the problem?

The redesigned version of _Data Analysis and Visualization in R for Ecologists_ was adopted today. This curriculum includes several links to episodes in the previous version, which will now produce a 404 error. I can suggest two possible solutions:

1. Replace those link targets with locations in the new version of the lesson that cover the same concepts/skills
2. Host a version of the lesson before the redesign was adopted, and adjust these links to point to the equivalent location in that site. ([This is the state of the repository at the last commit before the redesigned version was merged in](https://github.com/datacarpentry/R-ecology-lesson/tree/6a5ab5e94985b3b528bdb9b7455bf4f6b238e20c).)

**Comment by ethanwhite** [comment]
Thanks for the heads up @tobyhodges! I like option 1. If you have time for a PR it would be most welcome or alternatively a list of links that this breaks or a general way to check for them

**Comment by ethanwhite** [comment]
Close by #1036. Thanks again for the help @tobyhodges!
