### ISSUE TITLE
Update Python material to Python 3

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#145]
All necessary modules are now available in Python 3 and it will make teaching easier by removing common points of confusion like integer division. The most common thing we'll been to fix is changing print statements from:

```
print x
```

to

```
print(x)
```

**Comment by brymz** [comment]
Do you want me to back track to the beginning to make this shift while also
formatting? or plan to go through in a pass dedicated to updating to Python
3?

**Comment by ethanwhite** [comment]
Whatever you think is best if fine with me.

**Comment by brymz** [comment]
This ('Update Python material to Python 3') seems like the next long-winded task to get to in between active projects and priority issues. I plan to start in `materials/` and then do `exercises/`. Do you have any feedback or comments before I start? Would you prefer me to work on something else?

**Comment by brymz** [comment]
I think this `2to3` will be very useful (https://docs.python.org/3/library/2to3.html). I am not sure if it will also update `IPYNB`.

**Comment by ethanwhite** [comment]
Should we set up a meeting for next week to strategize on this and other things going forward?
