### ISSUE TITLE
Develop R-SQL Assignment and Exercises

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#178]
@ethanwhite I'll need some direction before I can make progress on this. Is there a package to work from? What kind of exercises do you have in mind?

**Comment by ethanwhite** [comment]
The lesson material is available here:
http://datacarpentry.github.io/R-ecology/06-r-and-sql.html

There should be one or two simple exercises to introduce the R-SQL interface - just running a simple query of a database from inside R. And then one or two more integrative exercises that combine a SQL query from inside of R with doing some manipulation or graphing or something.

**Comment by ethanwhite** [comment]
General exercise outline:

1. Super basic. Connect and simple SELECT query.
2. More complex, but still just SELECT query. (JOIN, FILTER, ORDER BY)
3. Get some data and do something with it. RSQL + analysis in R (graph, statistics).
4+ Putting things into database.

**Comment by brymz** [comment]
I'm having trouble figuring out how to connect to a `View` that we created in the `portal_mammals.sqlite` during the SQL assignments. Can I only interact with tables?
```
library('RSQLite')
myDB <- "portal_mammals.sqlite"
conn <- dbConnect(drv = SQLite(), dbname= myDB)
```
```dbGetQuery(conn, "SELECT count(*) FROM surveys")``` works.
```dbGetQuery(conn, "SELECT count(*) FROM No Missing Data")``` does NOT work.

**Comment by ethanwhite** [comment]
In this particular query there's an issue with the spaces in the name. You should be able to quote "No Missing Data". Not sure if there are issues beyond this.

**Comment by brymz** [comment]
I suspected it was an 'issue with spaces'. So, is it worth going back to rename the views in `portal_mammals.sqlite` to be camel case or underscored? I started writing exercises to only use the 'Surveys' table, but should be able to go either way pretty easy.

**Comment by ethanwhite** [comment]
> So, is it worth going back to rename the views in portal_mammals.sqlite to be camel case or underscored?

Definitely, having the spaces was modeling bad practice.

**Comment by brymz** [comment]
Now or aftersemester?

**Comment by ethanwhite** [comment]
Now is fine, but no rush.

**Comment by brymz** [comment]
Issue completed in #226.
