### ISSUE TITLE
Add an exercise that loops over multiple files

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#187]
A nice example of looping that applies to a lot of folks' research is to loop a bunch of different files doing the same thing to each file. We should develop a problem around this. If there's something in the Genomics lesson space (see: http://datacarpentry.github.io/lessons/) that works it would be nice to add a genomics exercise or two.

**Comment by brymz** [comment]
Would this be something like the gc-content question in Loops 2, but where
each file is a sequence? In this case, the loop would come before the
function as it calls in the file? Don't know enough about genomics to know
intuitively what you mean by a 'genomics exercise'.

**Comment by ethanwhite** [comment]
> Would this be something like the gc-content question in Loops 2, but where each file is a sequence?

That would work.

>  In this case, the loop would come before the function as it calls in the file? 

I don't quite follow the question.

> Don't know enough about genomics to know intuitively what you mean by a 'genomics exercise'.

Yeah, me either. Mostly what I meant was to take a look at the Genomics lessons on the lessons page and see if there's something easy enough for non-genomics people to understand that we could write an exercise or two around it. In particular I think the exercise you proposed could be made more realistic by using actual sequence file formats instead of just made up strings.

**Comment by brymz** [comment]
Ok. I've got a couple of hours left for the week once I finish adding the
subtitles. Is this what you want me to work on? Or is there something more
pressing? Do we want the subtitles to appear on the site or just be in the
files for reference?

**Comment by ethanwhite** [comment]
On 08/27/2015 01:18 PM, Zack Brym wrote:
> Ok. I've got a couple of hours left for the week once I finish adding the
> subtitles. Is this what you want me to work on? Or is there something more
> pressing?
Sure, that sounds good.
> Do we want the subtitles to appear on the site or just be in the
> files for reference?
I don't have a strong preference a priori.

**Comment by brymz** [comment]
Addressed in #204.
