### ISSUE TITLE
Add Tidy Data problems based on Data Carpentry messy data

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#190]
Rather than have students use a database with some problems for several weeks and potentially internalize poor structure, we've [switched over](e35d6c3c00764a40ce4f7dbbc9517e453e176671) to using the [Portal Project Teaching Database](http://dx.doi.org/10.6084/m9.figshare.1314459) for the main SQL exercises. This means we need messy data for database structure/tidy data problems.

Data Carpentry has messy data designed for looking at this problem. See, e.g.,
http://datacarpentry.github.io/spreadsheet-ecology-lesson/01-format-data.html

We should concert the current database structure problems to something based on this data, or add new "Tidy Data" problems based on this data and tweak the existing database structure problems to have the students download a the original database file that has all of the structural issues in it.

**Comment by ethanwhite** [comment]
@brymz - next time you have some hours this should be a high priority. Thanks.

**Comment by brymz** [comment]
Ok. Just finished creating data files for #187 (Loop with multiple files), but didn't get to writing the exercise. I'll make this (Tidy data problem) first priority next week and then resume #187 afterwards. Then #178 (R-SQL). Does that work?

**Comment by ethanwhite** [comment]
Sounds like a plan.

**Comment by ethanwhite** [comment]
Let's fix the broken solutions first and then this should be the next new thing. Thanks.
