### ISSUE TITLE
Update SQL answers to use Portal Teaching Database

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#192]
I called a last minute audible and switched to using:
http://figshare.com/articles/Portal_Project_Teaching_Database/1314459

for the database. All of the solutions are still based on the full dataset on Ecological Archives, so we'll need to update the solutions.

**Comment by brymz** [comment]
I see you're getting into the spirit of football season!

Is this a low priority compared to the exercises (#190, #187, #178)?

**Comment by ethanwhite** [comment]
No, this is a top priority since the solutions don't match the problems that they are working on right now.

**Comment by ethanwhite** [comment]
I just added a `highpriority` label to help ID things that should be at the top of the list.

**Comment by ethanwhite** [comment]
Was this fully closed by #194? If so, go ahead and close.

> I see you're getting into the spirit of football season!

Oh, and yes, as a new member of the Gator Nation I'm actually contractually obligated to :)

**Comment by brymz** [comment]
>Was this fully closed by #194?
#194 was just sql-1. I will finish sql-2 and close by the end of the day. 

> contractually obligated
That's a serious commitment.

**Comment by ethanwhite** [comment]
Great. Thanks.

**Comment by brymz** [comment]
Sql-1: #194
Sql-2: #198 (Sql-2 will also be updated, separately, to address #190)
