### ISSUE TITLE
Consider revising schedule.md

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#208]
While looking through the schedule.md, it struck me that we could organize the order of videos/readings to follow the order of the exercises. In my mind, the structure would look like:

- Topic 1 [reading link] | [video link]
- Topic 2 [reading link]
- Topic 3 [video link]
- etc.

**Comment by ethanwhite** [comment]
Sounds good.

**Comment by brymz** [comment]
This issue is upgraded by #209, so I will close this issue, planning to choose an organized structure that makes sense for the automation.
