### ISSUE TITLE
List big picture learning objectives w/assignments

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#211]

**Comment by brymz** [comment]
Are these listed anywhere currently? I have a good idea of the topics covered in each assignment and could relate them a set a of learning objectives, if you don't already have a set in mind.

**Comment by ethanwhite** [comment]
> Are these listed anywhere currently? 

Nothing here atm. There are learning objectives at the top most of the Data Carpentry and Software Carpentry materials that would be good sources for getting started.
