### ISSUE TITLE
Move table restructuring problems later in semester for next run

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#213]
Asking students to restructure messy tables after only 2 weeks of SQL is confusing and/or annoying. Students want to automate this, but they don't know how yet, and so it's either really repetitive or they spend a lot of time trying to learn something they don't have the background for.

Tidy-data-1.md is a better problem for early in the semester. The actual restructuring problems should be moved to late in the semester as an opportunity to revisit proper table structure while working on automated cleaning.

**Comment by brymz** [comment]
Do I incorporate these problems into the R-SQL Assignment (#178)?

Also, there seems to be some conflict with #212 if we move these problems. Linked with the R-SQL section, the restructuring would be automated and not by hand.

**Comment by ethanwhite** [comment]
We can't do anything with this mid-semester, it's just here as a note for later cleanup and improvement. I've added a new `aftersemester` label to indicate these.

**Comment by brymz** [comment]
@ethanwhite, Can you be more specific about what you want to happen here? Did you want these to go to the R-SQL Assignment? Should the exercise language be revised for automation?

**Comment by ethanwhite** [comment]
Yes, adding these to the R-SQL assignment and revising the language for automation is what I was thinking. More generally I'm envisioning expanding that assignment to generally talk about automatically tidying data, so a couple of exercises on using `tidyr` would be good there.

**Comment by brymz** [comment]
- scrap portal data
- long vs wide
- split columns with multiple values in single column

**Comment by brymz** [comment]
Decided to copy and revise `Scientific-tree-biomass-challenge-R.md` to use `tidyr` instead of the [EcoData Retriever.](http://ecodataretriever.org/): `Tidyr-tree-biomass-R.md`.

**Comment by brymz** [comment]
Add `tidyr ` vignette to readings: https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html

or R-blog: https://blog.rstudio.org/2014/07/22/introducing-tidyr/
