### ISSUE TITLE
Add exercise that exports data from Portal Database & imports to data frame

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#215]
This is for assignment r-2 and is intended to revisit SQL. This should be added to r-2.

**Comment by brymz** [comment]
For now or next semester?

**Comment by ethanwhite** [comment]
Now (hence the `highpriority` tag).

**Comment by brymz** [comment]
Ah. Tags don't come through in the email. I'll remember that.

**Comment by brymz** [comment]
Do you want the export of the data from the Portal Database to be a SQLite or R operation?

**Comment by ethanwhite** [comment]
SQLite, the class doesn't know how to do it from inside R at this point.

**Comment by brymz** [comment]
Word.
