### ISSUE TITLE
Add an integrative NEON problem

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#230]
I'd like to add a problem that uses NEON data for a big integrative problem. Download the data, put it in a database and/or loop over importing a bunch of different files, extract data from it using R, do an analysis creating a graph and/or some stats.

**Comment by brymz** [comment]
Something like this might come out of the NEON Hackathon (Oct 21-23). What's your timeline for this problem?

**Comment by ethanwhite** [comment]
The sooner the better on this one since the next couple of weeks will be all of the integration stuff.

**Comment by brymz** [comment]
I'm on it.
