### ISSUE TITLE
Output solution to Functions 2 is wrong

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#251]
It only has one answer and that answer doesn't fit with either of the problems.

**Comment by brymz** [comment]
Are these the answers? 
[1] 17150.56
[1] 24955.54

I think Functions-2-R.txt and Functions-3-R.txt are switched.

**Comment by ethanwhite** [comment]
yes

**Comment by brymz** [comment]
Done #252.
