### ISSUE TITLE
Clarify point 3.2 in Version-control-basic-5-R.md

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#269]
I couldn't find "two lines of code under `push an existing repository from the command line`". Can the instruction be more clear or include a link?

**Comment by ethanwhite** [comment]
Did you create a brand new repo without initializing it with a README?

**Comment by brymz** [comment]
I don't think so. I'm not sure I've initialized any of my repos with a README. I wanted to finalize my CH1 project before I make the repo inviting.

**Comment by ethanwhite** [comment]
My question relates to the fact that I'm confused that you don't see `push an existing repository from the command line`. Here's a screenshot of a brand new repository:

![screenshot from 2015-10-28 07 26 06](https://cloud.githubusercontent.com/assets/744427/10787180/356ae85a-7d45-11e5-8afd-1ab01ad3f616.png)

**Comment by brymz** [comment]
Ok. We're on the same page now. I was only checking my existing repos for
that language.
With the screenshot of a new repo, it looks pretty obvious to me. And now
that you've taught the lesson,
I'm sure you're aware of any issues that came up. Sorry for the confusion.
