### ISSUE TITLE
Size-biased-extinction file name change

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#286]
`Size-biased-extinction.md' does not match the file naming convention, but I'm hesitant to make a switch before we decide if that's important to us. The file name generally matches or paraphrases the title which is now 'Putting it all together' and includes the language. I can see any of these choices working: 'Putting-it-all-together-R', 'All-together-R', 'Put-it-together-R'. @ethanwhite, Let me know if you're ok with a change.

**Comment by brymz** [comment]
I got short-napped today... I've organized myself to set-up the code solution and the output solutions. It should be a straight forward integration. Once we decide on a file name, I might even just be able to rename some of the existing output solution files.

**Comment by brymz** [comment]
Oops.

**Comment by ethanwhite** [comment]
Rename away.

**Comment by brymz** [comment]
Aye, sir. It's done.
