### ISSUE TITLE
Add a style problem

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#298]
Provide a piece of code with lots of aspects of poor style and the exercise is to clean it up.

**Comment by brymz** [comment]
Are there any poor style examples that you want to be sure are included in the exercise?

**Comment by ethanwhite** [comment]
Off the top of my head the list would include:

* bad variables names (not descriptive, poor capitalization)
* no/inconsistent indenting
* bad spacing (around operators, parentheses
* lack of or bad comments for functions

**Comment by brymz** [comment]
As per https://github.com/datacarpentry/semester-biology/pull/305
