### ISSUE TITLE
Create R versions of all Python lecture material

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#3]

**Comment by ethanwhite** [comment]
@brymz is this complete now? If so let's go ahead and close this.

**Comment by brymz** [comment]
I think not. 

PR #154 adds links to on-line reading material outside of the course. I listed everything that I found. I sorted it to put the most content-accessible and relevent-to-the-course materials first in the list. There is a lot of information there that might be better organized (or condensed to a few key choices).

I have not made progress to create the slide or example materials you use in class.

**Comment by ethanwhite** [comment]
I looked at "lecture" and thought "exercise" sorry for the confusion.
