### ISSUE TITLE
^b --> <sup>b</sup>

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#31]
Strings-4-R.md vs Functions-3-R.md

**Comment by ethanwhite** [comment]
<sup>b</sup> because it will render properly.

**Comment by ethanwhite** [comment]
heh, that's `<sup>b</sup>`, appropriately rendered :smile:

**Comment by brymz** [comment]
Done.

**Comment by brymz** [comment]
Need to make sure all other exercises follow this formatting.
