### ISSUE TITLE
Integrate lecture/demo material

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#310]
There is some good, demo in class style, lecture material. This should be given appropriate YAML headers and should then be automatically integrated into the site with either (or both) a `Classroom Demos` page listing all of the available material or an additional column in the `Assignment Schedule` table.

**Comment by brymz** [comment]
Any objections to combining the `lectures/` and `material/` directories?

**Comment by ethanwhite** [comment]
Nope
