### ISSUE TITLE
Expand documentation 

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#311]
To make this really useful to other folks we need to substantially expand the documentation. Specifically we need walk throughs for:

- [x] Make a copy of the site for your own course
- [x] What to change immediately to customize this to your own course and how
- [x] How to add/modify exercises
- [x] How to add/modify assignments
- [x] How to change the schedule
- [x] How to contribute improvements and what kinds of changes should be submitted to the main repo
- [x] Style guide
- [x] CONTRIBUTING.md
- [x] How does the course work (i.e., flipped classroom, workshop format in class)

**Comment by brymz** [comment]
What would be the most effective way to name the documentation directory to make it easy to find?
My first thought was to name the directory `documents/`. I've also considered `help/` or either of these names with some arbitrary prefix (e.g., `_`, `!`) to put it at the top of the list.

**Comment by ethanwhite** [comment]
`docs` is the probably the most standard name for this sort of thing. Let's definitely not use arbitrary prefixes to float things to the top.
