### ISSUE TITLE
Add material on spatial analyses

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#313]
Make this a week of the course by combining weeks 3-5 into two weeks.

**Comment by brymz** [comment]
@ethanwhite, Can you be more specific about how you want to combine weeks 3-5? In the meantime, I can work on a spatial analyses assignment. Alternatively, NEON requested some active review/development of their spatial analyses lectures that we could use/modify.

**Comment by ethanwhite** [comment]
If NEON has exercises that would work I'm happy to adapt theirs (though they would need to be ported over to this repo, which would require them either having a good license or getting their permission. I definitely think that the NEON/Data Carpentry spatial material that you've been helping with should be the reading material for this section.

**Comment by ethanwhite** [comment]
I'm going to open another issue on combining weeks 3-5 to keep this one focused.

**Comment by brymz** [comment]
Is there anything in particular that you would like to accomplish / teach for 'spatial analysis'? 

I have raster data (digital surface and terrain models) for two sites from NEON to work with if I am to limit the reading materials to the http://data-lessons.github.io/NEON-R-Spatial-Raster/. The other option is to revisit the existing 'NEON 2' lesson (#254) that combines raster and vector data. This was developed further as an additional workshop http://data-lessons.github.io/NEON-R-Spatial-Vector/.

**Comment by ethanwhite** [comment]
Since we're doing a week on this I'd like to include:

1. Both raster and vector data and how to combine them (e.g., to get environmental variables at a set of sampling points.
2. Reprojecting
3. An integrated problem that uses spatial methods to generate a table of data and then produces a graph from it

So definitely include info from both sets of reading material, just probably not everything from both sets of readings.
