### ISSUE TITLE
Cull / integrate extra files.

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#318]
Please, object to any on the list if you disagree:

https://github.com/datacarpentry/semester-biology/blob/gh-pages/style-guide.md
https://github.com/datacarpentry/semester-biology/blob/gh-pages/compbioproj.md

**Comment by ethanwhite** [comment]
Go for it.

**Comment by brymz** [comment]
How about the .PY scripts in `tools/`? Cull or Integrate?

**Comment by ethanwhite** [comment]
Cull

**Comment by brymz** [comment]
How about `atom.xml` in the main directory? It looks like it is linked to `_posts/` directory that we deleted.

**Comment by brymz** [comment]
Maybe `atom.xml` is important. I get this error `jekyll 2.4.0 | Error:  Address already in use - bind(2)`.

**Comment by ethanwhite** [comment]
Let's just leave it then.
