### ISSUE TITLE
datacarpentry.org/lessons out-of-date

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#329]
The site says: 

"These materials are being used in a course at the Univeristy of Florida in Fall 2015. It is not currently meant to be fully comprehensible without additional context."

Now that we have `docs/` does that mean the site should be fully comprehensible without additional context?

**Comment by ethanwhite** [comment]
Yeah, let's go ahead and get rid of that.

**Comment by brymz** [comment]
Do you have any thoughts about what should it say, instead?

**Comment by ethanwhite** [comment]
I think it should get moved up into the established lessons section and have a sentence or two on what the course is for. Give it a go, submit a PR, and mention me and I'll be happy to come take a look.

**Comment by brymz** [comment]
Roger that.

**Comment by brymz** [comment]
PR at https://github.com/datacarpentry/datacarpentry.github.io/pull/64
