### ISSUE TITLE
Update markdown formatting

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#334]
As per #333.

**Comment by ethanwhite** [comment]
When you get this figured out can you also fix it for https://github.com/ethanwhite/progbio? I've added you as a collaborator.

**Comment by brymz** [comment]
Doesn't look like there is a `_config.yml` at https://github.com/ethanwhite/progbio. So, I'm not sure if anything needs to be done here.

**Comment by ethanwhite** [comment]
Ah right, perfect, thanks.
