### ISSUE TITLE
Condense weeks 3-5 into 2 weeks

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#338]
In the last run of the course weeks 3-5 felt a little thin to me in total, so I think we can combine them into two weeks. My specific thoughts (which are certainly open to discussion) involve:

1. The first week combines the current first week and the first two exercises from the second week. We should probably include a super simple data frame problem, so the 3rd problem from the 2nd week, but removing some of the more complex bits, at least including the use of `subset`.
2. The second week is then more advanced data frame stuff + dplyr. Since we're already showing them dplyr we can probably skip the part of the 4th problem from the current 2nd week that has them manually export data and then load it into R. Maybe move this problem to be the last problem of the new 2nd week and have them do the query from R using dplyr instead of doing the manual export.

What do you think? Is this still a reasonable amount of material in each of these two weeks for beginners? Any suggested changes to the plan for the reorganization? Other thoughts?

**Comment by brymz** [comment]
Are we going to keep the 'SQL Practice' exercise?

**Comment by ethanwhite** [comment]
Sure, I think a little basic revisiting of SQL on it's own isn't a bad thing, but I'm open to being convinced otherwise.

**Comment by brymz** [comment]
> I'm open to being convinced 

My concern is that we lose adequate time and brain power for new material by forcing it in with the condensed Intro-R weeks. If anything, I would put it right at the beginning of week 3 before moving on to R. Or leave it out and gauge the next run of class, inserting it if the need arises.

'Scientific 0' is the `dplyr` version of 'Data Frames 1'. Do you want to maintain the `subset()` and `object['colum_name']` subsetting material or just jump from 'here's what a data frame looks like'  to `dplyr?`

**Comment by ethanwhite** [comment]
OK, I think that's a good argument. How about moving it to the beginning of the Data Visualization assignment?

I'm leaning towards jumping straight to `dplyr`. What do you think?

**Comment by brymz** [comment]
'SQL Practice' to Data Visualization assignment, aye.

Straight to `dplyr` seems the DC model and helps clean the merge of weeks. If anything, detailed subseting operations can be introduced with the R Fundamentals assignments.

**Comment by ethanwhite** [comment]
:+1:
