### ISSUE TITLE
Managing merge conflicts with restructuring and markdown formatting

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#340]
There are a few issues still open and some changes that need to be made to get the site put back together after our reshuffle: 

#324 should be able to get merged anytime
#333 is also ready to go, but needs a simple edit (space between header) in all of the `assignments/`
#339 modifies multiple `assignments/` files and would cause a merge conflict if I go on to make changes for markdown updating. The remaining issues (#213, #313) could also cause merge conflicts in `assignments/`

What is the best way to go about avoiding merge conflicts? My idea is to make a branch from the already edited `combine-weeks` branch that corresponds to #339 and then make the remaining changes necessary for #333. PRs for to #212 and #313 would also then be branched from `combine-weeks` unless #339 is merged before I get started later today. In the meantime, I'm going to review the NEON spatial data lessons.

**Comment by ethanwhite** [comment]
Merge conflicts can be hard to avoid in these sort of complex restructurings and so in some cases we may just have to do the merge and manually rectify the conflict. Sometimes in these cases `rebase` can be your friend. We can talk about managing all of this when we chat later today.

**Comment by brymz** [comment]
Take home message: If there is a base set of changes that affect the next change, it is ok to make a branch from the first modified branch; however, the nested branch may cause merge issues on github.com and require merging from the command line

We avoided this by merging in the first branch `combine-weeks` before getting to the 'next change'.
