### ISSUE TITLE
Update urls to gh-pages links

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#35]
(Subtask of #1 )

OLD: [Functions 5]({{ site.baseurl }}/exercises/Functions-5/)

NEW: [Functions 5]({{ site.baseurl }}/exercises/Functions-5-R/)

**Comment by ethanwhite** [comment]
You shouldn't need the .md I don't think.

**Comment by brymz** [comment]
Cool. Well, some of the names have changed, so I'll have to check on the
second pass anyway.
