### ISSUE TITLE
Broken Link: 

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#371]
http://nbviewer.ipython.org/url/raw.github.com/ethanwhite/progbio/master/materials/rpy2_demo.ipynb

Please advise.

**Comment by ethanwhite** [comment]
Correct link is:
http://nbviewer.jupyter.org/github/ethanwhite/progbio/blob/master/lectures/rpy2_demo.ipynb

**Comment by brymz** [comment]
Thanks!
