### ISSUE TITLE
Sidebar Functionality

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#384]
- The browser window can be set so that some of the sidebar is never visible. You can scroll on the content page, but not in the sidebar.
- In a small screen the sidebar moves above the content panel so that any navigation returns to the sidebar and requires scrolling to content.

**Comment by brymz** [comment]
There is no theme within Hyde to make either of these changes. I would have to work out a custom fix in the `.CSS` or set up a different theme if this was determined to be an important issue. Are there a lot of users with small screens?

**Comment by ethanwhite** [comment]
Let's chat about this next time we talk since I'm not sure I fully understand what you're interested in doing here.

We shouldn't feel restricted to Hyde, we can always change themes if we need to.

**Comment by ethanwhite** [comment]
One option would be to reduce the total number of items in the sidebar to something like:

* Schedule
* Materials (i.e., elements)
* Getting Started (Having similar material to the For Students & For Instructors sections of homepage with additional background + a link and information for self-guided students)
* About (including docs, current About page, and Github link)

**Comment by brymz** [comment]
We might also consider reducing or removing the `site.description`: "Teaching biologists the tools they need to use computers to do cool science".

**Comment by brymz** [comment]
Here's my plan for this:

1) `mkdir main/`. Alternately,`home/`, `start/`

2) `mv computer-setup.md schedule.md START-for-self-guided-students.md syllabus.md main/` 

3) `mv LICENSE.md docs/` and/or `about/`

4) Fix broken links

5) `mkdir nav/`

6) In `nav/`, `course-materials.md`, `getting-started.md`, `about.md`, with links and descriptions of elements

7) Update `sidebar.html`

8) Update `site:description`

9) Update `docs/`

**Comment by ethanwhite** [comment]
So, is the idea that the file location restructuring will be reflect in the site layout? Are you envisioning the things in `nav/` as the things that will appear on the side bar? I'm just trying to understand how all of this relates to the overarching issue.

**Comment by brymz** [comment]
That's what I'm thinking. The `nav/` keeps the extra files out of the root
directory and takes the place of a dropdown menu or site map.

**Comment by brymz** [comment]
I've opened a PR #393 that is ready for review. `docs/` will need to be updated to reflect a new navigation structure.

I am closing this issue, but will reopen it if we reject #393 and/or decide to consider other options.
