### ISSUE TITLE
Update exercise structure

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#388]
As per #380.

**Comment by brymz** [comment]
I think I'm ready to move forward with this. My plan is to develop an overlapping file name and yaml tag system. The new exercise file name would be generalized to `topic`-`title`-`language`.md. I was concerned about the organization of the file structure with names instead of numbers, but decided that all instructors and developers should have access to the website. As long as the course is well documented and organized on the website, the file structure should be manageable. The process for this:

1) Check `exercise/` `title` and `subtitle` for best naming. *This is the only part that I'm hesitant to automate. I think automation could get very case specific. I have to browse through all of the files for the check anyway.*

2) Rename `title` something for a placeholder: `old_title`.

3) Update yaml tags: `old_title` -> `topic`, `subtitle` -> `title`.

4) Update `assignments/` lists: `title` -> `subtitle`.

5) Rename `exercise/`, `output/`, `datacarp-semester-biology-solns` files.

6) Update 'follow-up' links.

7) Remove `old_title`.

8) Update `exercise/index` for `topic`-`title` organization.

**Comment by ethanwhite** [comment]
OK, sounds good. :+1:
