### ISSUE TITLE
mv content of exercises/README to docs/ 

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#396]
`exercises/README.md`

The names of all exercise files should start with a capital letter.

This is a temporary solution to an issue with how Jekyll processes pages.

Jekyll currently processes pages in alphabetical order. This results
in cases where, when the name of an exercise included in an assignment
comes after the name of the assignment alphabetically, the
assignment page is processed before the exercise and the list in the
exercise is not properly converted to a list.

By naming all of the exercises to start with captical letters, and
therefore come before the names of the assignments (which are all lower
case) alphabetically.

**Comment by brymz** [comment]
From what I understand about Jekyll development, organizing `assignments/` and`exercises/` as `collections` ([Documentation](https://jekyllrb.com/docs/collections/)) might resolve this processing difficulty.

**Comment by brymz** [comment]
Paraphrased in committed change: https://github.com/datacarpentry/semester-biology/pull/395/commits/89d209ad9573fd3969e732d1318a6bbde7e967ec

**Comment by ethanwhite** [comment]
> From what I understand about Jekyll development, organizing assignments/ andexercises/ as collections (Documentation) might resolve this processing difficulty.

Nice find! It would be great to try this out since I hate that hack. I'd suggest opening a new issue for it and closing this one if it's handled in 89d209a.

**Comment by ethanwhite** [comment]
Beat me to the 2nd part :smile:

**Comment by brymz** [comment]
Beat you to both parts - #400 ;-)
