### ISSUE TITLE
What is the best way to share .SH scripts that correspond to a commit?

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#398]
I have written .SH scripts that automate revision of the website structure. Many of these scripts directly correspond to a commit (e.g., 177d6815a5169ece456c7bcb32aaa57ce59a14ed). I'd like to store them somewhere (other than locally) for reference to the commit, but I'm not sure they belong in the repo.

I don't think they belong in the repo because they are specific to the website restructure at the current version of the website. As a future task, I might try generalizing the script to check or maintain consistency in the file structure. For instance, there would be a script that would repair file names and links if you changed the title of an exercise. These scripts would definitely belong in the repo.

**Comment by ethanwhite** [comment]
I agree that as they stand they probably don't belong in repo at the moment. You could post them as gists and include the link to the gist. Or, if it's a short script, you could even include it in the commit message itself.

**Comment by brymz** [comment]
Are the scripts something you would like to see? or are the results (i.e., committed changes) sufficient for the PR review?

**Comment by ethanwhite** [comment]
Results are all I need. Doesn't matter if you did them by hand or automated them.
