### ISSUE TITLE
list : data.frame :: vector : matrix

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#40]
(Subissue of #12)
 
Ran into subtle differences for output from Functions-5 and Functions-6

Now, that I have an explanation I wonder if/where it fits in the curriculum.
https://twitter.com/ZackBrym/status/595651701945794561

It might fit along with our introduction of `dplyr` [[Documentation Link] (http://cran.r-project.org/web/packages/dplyr/vignettes/introduction.html)].

**Comment by ethanwhite** [comment]
Yes, we'll definitely need to talk about these different types. I think we'll have a better idea once we start looking at the overall flow for the course.

**Comment by brymz** [comment]
>> once we start looking at the overall flow for the course.
As in my response to #39, do you have a goal for when and how you'd like to
establish the 'flow idea'? soon? after I finish the first pass of intro
course exercises? way later?

**Comment by ethanwhite** [comment]
"when I find time" :)

**Comment by brymz** [comment]
::chuckle chuckle::

Ok. Seems we've worked out a strategy for the meantime.

**Comment by brymz** [comment]
PR #160 should suffice for an introduction to vectors and data.frames.
Do we still want to include exercises to explore data types (numeric, character, logical, factor)? 
Do we 'ignore' lists and matrices in exercises (with maybe some commentary in lecture? I don't really see them as being important to working with data.

**Comment by ethanwhite** [comment]
That sounds like a good plan to me.

**Comment by brymz** [comment]
So, create new exercises for data types. (Leave out lists and matrices.)?

**Comment by ethanwhite** [comment]
I guess I'm not sure we really need "data type" exercises, so much as having at least some exercises for both vectors and data frames.

**Comment by brymz** [comment]
Roger that. We have exercises for vectors (Vectors 1, Vectors 2) and data frames (Data Frames, Scientific 0, Statistics 2, etc).
