### ISSUE TITLE
Consider fragility of course structure

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#413]
- Generate script to check repo for configuration and/or automate changes.
- Integrate with Travis CI.

**Comment by brymz** [comment]
I will need some direction to get started on this.

**Comment by brymz** [comment]
- [ ] File name capitalization for `exercises/`, `readings/` and `lectures/`
- [ ] File name match for `exercises/` and `solutions/`
- [ ] `title` match for `schedule`, `assignments/`, `readings/`, and `lectures/`
- [ ] `lectures/` and `solutions/` updating to `exercise/` edits or new software version release

**Comment by ethanwhite** [comment]
Since @brymz is out of significant time for this I think I'm going to close it and see how things play out as more folks get involved. If we run into issues we'll address what we see rather than trying to anticipate too much.
