### ISSUE TITLE
(aside text) to ( aside text ) with italics

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#428]
As per #421 
"Decide on (aside text) vs. (*aside text*) vs. ( *aside text* ) and make necessary edits"

I think ( *aside text* ) best distinguishes the parenthetical text from the main text and also matches the formatting of (`object`) which appears to place a space between the `(``)` and the text. 

Do you have any strong feelings about this formatting change?

**Comment by ethanwhite** [comment]
Sorry, I'm not remembering exactly what you mean by (aside text). Can you give me an example?

**Comment by ethanwhite** [comment]
Ah, I see now. I prefer (_aside text_). It's a nice compromise between clearly distinguishable and not looking odd as standard written text.

**Comment by brymz** [comment]
Ok. I will leave it as is then. Is seems working in `bash` has clouded my ideas about 'standard written text'.
