### ISSUE TITLE
Replace _ with - for file names?

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#429]
As per #421.

Do we want to use `-` for space in file names across the board? 

Currently, `materials/` and `code/` have names that use `_` and `-`. `data/` files are all `_`.

**Comment by ethanwhite** [comment]
Yeah, I've grown preferential to `-` for file names since it's definitely the more common practice. Also @ctb complains if you make him hit the shift key when typing the name of an executable, so I'm trying to avoid his wrath.

**Comment by brymz** [comment]
I will get to this after #422 gets merged, to avoid conflict.
