### ISSUE TITLE
Get data for spatial analysis lesson

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#438]
We are working to develop a spatial analysis lesson (#313). We have been involved with developing reading materials with NEON (http://neondataskills.org/tutorial-series/raster-data-series/ & http://neondataskills.org/tutorial-series/vector-data-series/) as a starting point for our lesson. The goal is to go a step beyond the exercises in the NEON material, which requires a bit of extra data as per the lesson plan and data requirements for the proposed spatial analysis exercise. 

### Lesson plan
- Generate `canopy_height` model for two sites with varying vegetation structure
    - `canopy_height = surface_elevation - terrain_elevation` 
    - Similar task to http://neondataskills.org/R/Raster-Calculations-In-R/
- Identify plots at each site
    - Use `points` or `polygons` from vector
    - Similar task to  http://neondataskills.org/R/crop-extract-raster-data-R/
- Visualize seasonal changes (*phenology*) in vegetation structure
    - Use multiple rasters (*time series*) for each site
    - `NDVI` or comparable metric for vegetation structure
    - May require reprojection to line up `NDVI` with `canopy_height` 
- Compare vegetation structure (`canopy_height`) for site to seasonal phenology (`NDVI`)
    - forested plot has a gradual seasonal shift in phenology
    - grassland plot has pulsed or less 'green' shift in phenology 

### Data Requirements
- Two elevation raster images per site from LiDAR
- One point or polygon vector for each site
- ~12 NDVI raster images per site from satellite (MODIS or LANDSAT)

**Comment by ethanwhite** [comment]
@sdtaylor or @MarconiS: As part of your role helping out with the labs training efforts, could one of you work with @brymz (a recent graduate from Morgan's lab who is working with me on the Data Carpentry semester long course) get the MODIS data he needs for this exercise  in the form he needs it?

**Comment by MarconiS** [comment]
I will be more than happy to do it, of course! Eventually if Shawn is interested too, we can synchronize and show different ways of downloading and using MODIS data in R

**Comment by sdtaylor** [comment]
Yeah, piece of cake to get this. I'd recommend converting the modis data to
tif and a common projection. Wrangling them out of the original hdf files
can be a hassle. I've got the gdal commands to do it written down somewhere.

On Jul 27, 2016 2:56 PM, "MarconiS" <notifications@github.com> wrote:

I will be more than happy to do it, of course! Eventually if Shawn is
interested too, we can synchronize and show different ways of downloading
and using MODIS data in R

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/datacarpentry/semester-biology/issues/438#issuecomment-235684476>,
or mute the thread

**Comment by brymz** [comment]
Great, @sdtaylor & @MarconiS! I'm ready to draw up the lesson anytime. I just need the data to get started. Let me know if you need any clarification or run into a snag. Thanks for the help!

**Comment by sdtaylor** [comment]
The resolution of the neon rasters is 1 meter, so I think it'd be better to use landsat (30m) instead of modis (250m). But 250m modis pixels would still work if landsat is too cloudy. I will check out the landsat images to see if there is a cloud free year at these sites.

**Comment by MarconiS** [comment]
Great idea indeed Shawn!
One thing I didn’t understand though is if you need the raster already Zack, or if you’d like make the students directly download them during the lesson. In the former case, it will be easy enough to use Landsat data, in the latter, I suspect, if we want to make the students download the tiffs in batch, it should be done outside of R (python or shell?). Maybe I am wrong though, since I am relatively new with Landsat data

Sergio Marconi,
MSc in Forest and Environmental Sciences

US - Italy Fulbright sponsored
PhD student in Interdisciplinary Ecology
University of Florida (SNRE)
Weecology Lab,
1746 McCarty DR #150,
Gainesville, FL 32611

On Aug 1, 2016, at 12:18 PM, Shawn <notifications@github.com<mailto:notifications@github.com>> wrote:


The resolution of the neon rasters is 1 meter, so I think it'd be better to use landsat (30m) instead of modis (250m). But 250m modis pixels would still work if landsat is too cloudy. I will check out the landsat images to see if there is a cloud free year at these sites.

**Comment by brymz** [comment]
> use landsat (30m) instead of modis (250m)

The vector / shapefile with the site plots will be set up arbitrarily (by you guys, I hope?!) to match the resolution of the satellite images. You could even pick around clouds if that became an issue. I'm thinking about 5 plots/site would work well. 

> Do you need the raster? or make the students directly download them during the lesson?

I would like to have a direct link to a `zip` of the data for this lesson. In previous lessons with 'complex' data download operations (e.g., http://www.datacarpentry.org/semester-biology/exercises/Loops-multiple-files-R/), we've also included links to the website database for students that are interested to checkout. So, both could be cool, but the `zip` of the whole data package, for sure. 

Thanks!!

**Comment by sdtaylor** [comment]
I think I have everything needed using the modis data. Sergio is looking at the landsat data, so if it's not too cloudy it may be a better option. 

[zip file](https://drive.google.com/file/d/0ByNGBGdHMdc2WkRCQVNoRHdhWnc/view?usp=sharing)

contents: 
./harvardNDVI/  - a years worth of bimonthly NDVI tifs for the harvard site
./sanJoaquinNDVI/ - years worth of bimonthly NDVI tifs for the sanJoaquin site
./create_dc_ndvi_data.R - script to make all the tifs from downloaded modis hdf's if your curious
./plotLocations/  - plots for the 2 sites made randomly in qgis.

**Comment by brymz** [comment]
This is great, @sdtaylor!

I'm working to set up the lesson solution and have run into a problem with the plot locations.
It doesn't seem like they line up with the right units. I used `readOGR()` to pull in the `shp`.

```
> extent(chm_harv)
class       : Extent 
xmin        : 731453 
xmax        : 733150 
ymin        : 4712471 
ymax        : 4713838

> plots_harv@coords
     coords.x1 coords.x2
[1,] -72.17442  42.54048
[2,] -72.16620  42.53807
[3,] -72.16648  42.53402
[4,] -72.17259  42.53412
[5,] -72.17808  42.53421
```

**Comment by brymz** [comment]
> It doesn't seem like they line up.

Brilliant, @sdtaylor! The reprojected data works great!! Novice mistake on my part.

**Comment by brymz** [comment]
> ./harvardNDVI/ - a years worth of bimonthly NDVI tifs for the harvard site
> ./sanJoaquinNDVI/ - years worth of bimonthly NDVI tifs for the sanJoaquin site

Could you tell me more about the two `xml` files in the NDVI directories? We might consider removing them if they are not important to save having to exclude them from the loop to extract NDVI values at the plots.

**Comment by brymz** [comment]
> Want me to change all the prefixes to the NEON codes and send another zip?

That would be great!

**Comment by sdtaylor** [comment]
An interesting note on the extents. Sometimes the packages in R will take care of different CRS's for you. Like if you were to use raster::extract() with a raster and point file of different CRSs, it will do the extraction and spit out a note saying the CRS on one of them was changed. But raster::crop() will not do this automatically, and you have to explicitly make the CRS of both inputs to crop() the same.

**Comment by brymz** [comment]
Any idea why I am having trouble importing `harvardPlots.shp` if I move it into the root ('working') directory?
'''
> plots_harv <- readOGR(".", "harvardPlots")
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
'''

**Comment by brymz** [comment]
> Sometimes the packages in R will take care of different...

R developers often try to make sure those kinds of default options are present. We teach students to include those 'optional default' pieces to make sure there are no surprises behind the scenes.

**Comment by sdtaylor** [comment]
movign it into the working directory works for me. did you move all the `harvardPlots` files or just the `.shp` file?

**Comment by brymz** [comment]
Ok. I only moved the `shp`. That was my other question. Are all of those files necessary? The `zip` that we provide the students should not have any extra files.

**Comment by sdtaylor** [comment]
yep, all files are necessary. any shapefile you get from anywhere will have multiple files like this.

an alternative would be to provide a csv of the lat longs and import them that way, which would be a single file. ecology people are likely to see either scenario.

**Comment by brymz** [comment]
Let's keep the shapefile set for now, then. We can hold onto the `csv` option to simplify the exercise later on if need be.

**Comment by sdtaylor** [comment]
[here](https://drive.google.com/file/d/0ByNGBGdHMdc2ZUJ3R2R6SjMzWWM/view?usp=sharing) are the materials with the fixed naming scheme.

**Comment by sdtaylor** [comment]
I looked at the NDVI time series, and the HARV site looks pretty funky in the spring. That's due to snow. The SJER site has a very nice ndvi curve.

**Comment by brymz** [comment]
It looks like real data! It will be a good talking point for students. Thanks for putting it together. 

I'll put out a pull request shortly with a draft of the lesson. Feel free to comment on exercise content and the solution.

**Comment by brymz** [comment]
Can you give me a brief statement of where / how you got the MODIS data? I'm thinking something along the lines of: "The data from MODIS was downloaded from an online repository from *some_govt_agency* (*link_to_site*)."

**Comment by sdtaylor** [comment]
Short:
The data from MODIS was downloaded from an online repository maintained by the USGS and NASA. It's freely available to anyone. https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table

Long:
[MODIS Products Table](https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table) - This is all the different modis data you can download. They are all at different temporal spatial scales. This data was from MOD13Q1. 

Click on a product and it will go to a page with some metadata about it. Everything is downloaded via a giant file server at [http://e4ftl01.cr.usgs.gov/MOLT/](http://e4ftl01.cr.usgs.gov/MOLT/). The products are again listed on the file server, and inside the folder for each one are the dates available for that product. Something that is only released once a year, like landcover, and 1 folder per year. MOD13Q1 is released every 16 days, so has 23 dates for every year.

Inside each date folder are the tiles for the entire earth. The hdf files are the actual data files, and there are also jpg files for a quick preview of them. I've never downloaded the xml files. As of July 2016 downloading from this server requires signing up for a free account.

Which tile should you download for your particular spot? MODIS data is split into a grid system over the entire earth. Check out the map [here](https://lpdaac.usgs.gov/dataset_discovery/modis). I can usually eyeball where things are, but sometimes I'm off and download the wrong ones. For this data HARV is in tile h12v04, SJER is in h08v05. 

The raw hdf files actually contain several layers in them, which are described on the respective product page under the Layers tab.
