### ISSUE TITLE
Make sure SQL material matches current version of Portal Project Teaching Database

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#441]
I just noticed some language that references old table and field names. This was in #422, so it's possible it's just in lectures, but we want to make sure everything matches the current state:
https://figshare.com/articles/Portal_Project_Teaching_Database/1314459

**Comment by brymz** [comment]
- [ ] check `solutions/`
- [ ] lower case table names in code solution
- [ ] fix variable names in `exercises/`

**Comment by brymz** [comment]
`Basic-queries-select-SQL.md` references the metadata on Ecological Archives. Is that still relevant? Is there a teaching set of metadata?

**Comment by ethanwhite** [comment]
Yes, I think so. There isn't a teaching equivalent so this is still the best source for reading up on the data and the study.
