### ISSUE TITLE
Allow `schedule` to work with missing readings/assignments

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#445]
In some cases it is useful to put items on the schedule that do not have associated readings or assignments (e.g., an introductory week, a week where material is presented but there is no associated assignment - see discussion in #443, weeks for working on projects). Therefore `schedule` needs to support this.

**Comment by brymz** [comment]
In #416, we decided to check that both `title:` and `language:` matches among `assignments/`, `readings/` and `lectures/`. Keeping that with the 'missing pieces' functionality demands some complexity and another decision moving forward.

The `assignments:` list in `schedule.md` requires that `title:` are unique across `language:`. I can keep the check for now (I think I've figured out how), but functionally I don't think it matters much. We may consider simplifying away from the language check or revisiting the `assignments.html` to also include lessons with the same `title:` but different `language:`

**Comment by ethanwhite** [comment]
I couldn't tell if you were looking for feedback from me or just adding notes. If it's the former, let me know.

I also just realized is that one option would be to just include empty/dummy files if needed, but if you think you can get this working by the end of the week that won't be necessary. If it turns out to be too tricky given the timeline just let me know and I'll dummy them in for now.

**Comment by brymz** [comment]
I have something working without dummy files and the `language` match.

I was looking for feedback whether you would prefer a simpler `assignments.html` without the language match or a solution (perhaps for later) that allows duplicate `title:` sorted by `language:`

**Comment by brymz** [comment]
My last statement was unclear: I have something working without dummy files and WITH the language match.

**Comment by ethanwhite** [comment]
If you've got it working with the language match let's just go with that. I don't see any strong reason to change anything else in the process.

**Comment by ethanwhite** [comment]
Oh, and nice work getting this figured out so quickly. You're definitely making Jekyll dance to your tune!

**Comment by brymz** [comment]
Where there is a 'missing piece' you can choose: 
* link 'back' to `schedule` (ready to go)
* black or grey image with no link
* blank space

**Comment by brymz** [comment]
Where there is a 'missing piece' I chose: grey image with no link. This can be modified easily to alternate specifications.
