### ISSUE TITLE
New schedule not finding Lecture if that is the only piece of material

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#454]
Looking at #453 locally, the schedule doesn't recognize the lecture material even though I believe the title is a match.

**Comment by brymz** [comment]
I tested that scenario with my updates, yesterday. Are you specifically referring to the `Knitr` week. `materials/knitr.md` is not a `lecture` unless there were changes to the `element:`

**Comment by ethanwhite** [comment]
Oops. Thanks. Let me fix that real quick.

**Comment by brymz** [comment]
So, the `title:` has to match AND the `element: lecture`.

**Comment by ethanwhite** [comment]
That took care of it. Apologies for the noise.
