### ISSUE TITLE
Consider `SpatialPointsDataFrame()` for `first-day-demo.R` and `lectures/r-spatial.md`

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#465]
As per #462

**Comment by brymz** [comment]
I noticed that in `materials/for-loops-R` the `collar-data-2016-01` is spatial data, but you did not use `SpatialPointsDataFrame()`. I did not find it necessary to introduce in `lectures/r-spatial` for the NEON material as most of the raster is already in a spatial object class. I do not have a strong argument to include `SpatialPointsDataFrame()` in the lecture material and recommend replacing it with `data.frame()` in `first-day-demo.R`.

**Comment by ethanwhite** [comment]
I'm actually working on this how for Friday. One of the things that's missing is how students can get their own data into the spatial realm and that's how I'll introduce it. The goal for the first day demo was to demo actual spatial work, not a general data frame class.

**Comment by brymz** [comment]
That makes a lot of sense to me. I could be free any part of today or tomorrow morning to help and/or review.

**Comment by brymz** [comment]
0e84b0052431b1468d1ddbe3496ae070e9f08323
