### ISSUE TITLE
Answer to Intro SQL #8 probably not quite right

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#469]
> Write a query that returns the number of individuals of all species combined (total_abundance) in each year, sorted chronologically. Include the year in the output. Save it as total_abundance_by_year.

A student reports that if you `COUNT(*)` to count all of the individuals you get a different answer that the one of the site, but if you `COUNT(species)` you get the same answer. We should either clarify #8 to make the current answer correct or update the answer to `COUNT(*)`.

**Comment by ethanwhite** [comment]
Tagging @andrewmarx so he's aware for grading. Either version of the count is OK for this year.

**Comment by brymz** [comment]
You can also do `COUNT(*) WHERE species_id IS NOT NULL`.

I have updated the language of the exercise to be 'known species' to reflect this desired answer. Stand by for PR.
