### ISSUE TITLE
Answers to Intro SQL #2-#4 incorrectly include `record_id`

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#470]
Answers to 2.2, 3 and 4 in the intro SQL assignment all include `record_id`, but there is no indication in the questions that they should. `record_id` should be removed from the output.

**Comment by ethanwhite** [comment]
Tagging @andrewmarx so he's aware for grading. Either with or without `record_id` is OK for this year.

**Comment by brymz** [comment]
I only found `record_id` in 2.2 (`Basic-queries-select-SQL-2.txt`) and 3 (`Basic-queries-where-SQL-[1-3].txt`). Changes made. Stand by for PR.
