### ISSUE TITLE
Rerun answers to last SQL-intro query

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#473]
From an email from a student:

```
For the last homework problem, I am having a little bit of trouble getting the output to look exactly like the output shown on the website.

Here is the code I am using:

SELECT  species_id, year, COUNT(species_id), ROUND(SUM(weight/1000.0),3) AS total_biomass_kg
FROM surveys
WHERE species_id IS NOT NULL
GROUP BY year, species_id

This gives me the correct answer, except for the total_biomass_kg column which isn’t rounding exactly like your output. Specifically, in your output, you have the following rows:

"OL",1978,47,1.1480000000000001
"OT",1978,66,1.161
"OX",1978,1,
"PE",1978,17,0.28600000000000003

When I try to get the OL and PE rows to round to those decimal numbers, the other answers also have several decimal places behind them and don’t look like the output. Everything else in the problem is correct. Should I be concerned about this rounding issue? If so, can you help me fix it?
```

I expect the updated version of SQLite Manager is just handling the floating point numbers more cleanly in the output so we probably just need to rerun the output to match.

**Comment by brymz** [comment]
I have confirmed I am on the same version of SQLite Manager.

The code we have stored for a solution is `SUM(weight)*0.001`. This student has to use `ROUND` because as a work-around from the integer division of `1000`. Do you recommend we `ROUND` our answer?

**Comment by ethanwhite** [comment]
There's also some weird order of operations floating point stuff here since `SUM(weight) * 0.001` and `SUM(weight * 0.001)` slightly different outputs. I think the use of the `ROUND` is an attempt to force long floating points from `SUM(weight * 0.001)` to look like the shorter versions from `SUM(weight) * 0.001`.

Short version - I think our answer is totally fine, but there are a bunch ways to solve this and the details change what the output looks like. I told them today to not worry about subtle things like this where they've clearly got the right answer so let's just not worry about this anymore. Thanks for helping run this down.
