### ISSUE TITLE
Add new Fall 2016 `materials/` to `materials/index`

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#488]

**Comment by brymz** [comment]
I wrote a `bash` test to find the handful of new files that you've added and was surprised by the lot that was returned to me. So,

Do we want all of the files in `materials/` on `materials/index`?
Should I take the opportunity to update `IPYNB` links from `ethanwhite/progbio` to `datacarpentry/semester-biology`?

**Comment by ethanwhite** [comment]
* Can you post the list of files in `materials`.
* Image files that aren't referenced should probably just be removed
* At this point I think the IPYNB's are probably pretty rusty, so my initial thought is either not publicize them or even remove them. Thoughts?

**Comment by brymz** [comment]
> Can you post the list of files in `materials`?

There are 143 of them, which is why I was thinking the best way to list them for review would be organized on `materials/index`. Otherwise, where do you recommend I post the list?

> Image files that aren't referenced should probably just be removed.

I mostly agree. The handful I would consider holding on to are `databases-basic-table-structure.png` and `databases-crosstab-table.png`. They aren't used in the current version of `database-structure.md`, but could be useful in the future. (*A side note, I was surprised to see you remove this material from your SQL lectures. Perhaps you found you covered the material actively in `tidy-data.md`, but it seems glossed over from the notes.*)

> I think the IPYNB's are probably pretty rusty

That's probably true compared to the progress we have made with the R materials. I think most of them are still pretty strong, perhaps better than some of the accompanying `MD` notes and they are what remains of any Python material. Again, I think organizing them will help us make a thorough investigation of the state of things. I do support removing files that are confusing or incomplete.

You bring up an interesting point about keeping files while not publicizing them. Does that mean we intend to get back to them to make them publishable? They were published at one time as 'Programming for Biologists'. Otherwise, what is their purpose unpublished but present in the directory?
