### ISSUE TITLE
Replace 'Basic Queries GROUP BY' exercise with something that requires GROUP BY

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#490]
Every year, despite instructions not to, one or more students solve this using DISTINCT. It's hard to say that's wrong, because it works, but it's not the goal, so we should just replace this question with someone better.

**Comment by brymz** [comment]
Will we want to create an `aftersemester` branch for the patch on this issue?

**Comment by brymz** [comment]
Is `GROUP BY` just a visualization tool if there is no aggregation? We could write the new exercise to set up `Aggregation-count-SQL.md` or `Aggregation-sum-SQL.md`. Otherwise, we could easily rewrite the existing problem to where we `GROUP BY` month (*instead of 'no duplicates' and 'chronological order'*) or `GROUP BY` plot (*instead of 'chronological order').

**Comment by ethanwhite** [comment]
> Will we want to create an aftersemester branch for the patch on this issue?

Yes, I guess we probably should.

> Is GROUP BY just a visualization tool if there is no aggregation?

Since you're just displaying grouped fields it ends up working just like `DISTINCT`. I think we should just move straight to using it for aggregation. Since we already have a couple of aggregation queries including one that's pretty simple, maybe we should just remove this question entirely.

**Comment by brymz** [comment]
> maybe we should just remove this question entirely.

I think I agree that we could remove `Basic-queries-group-by-SQL`.  `Aggregation-count-SQL` is pretty simple, but maybe we will want to include a hint or mention of `GROUP BY` in the exercise as it is being introduced.

**Comment by ethanwhite** [comment]
Sounds good to me.

**Comment by brymz** [comment]
I have pushed changes to `brymz/semester-biology/group-by` and will try to figure out how to create a `datacarpentry/semester-biology/after-fall2016` for a PR.
