### ISSUE TITLE
Assignments as notebooks

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#491]
RStudio has recently released [notebook functionality](http://rmarkdown.rstudio.com/r_notebooks.html) that could be really useful for handling R assignments. In short, we could have the questions in a notebook along with empty (or partially populated) code cells where the students code the answer. This would allow us to force consistency in the structure of the assignments and also put us in a position for potentially setting up test based auto-grading down the line. The biggest challenge would be maintaining modularity. Since the notebooks are just RMarkdown I think this is probably possible, but it will take some meaningful time investment to get right.

**Comment by brymz** [comment]
I like the concept, but am a bit hesitant of the implementation. For one thing, it looks like the notebook development is still pretty fresh and we would probably want to wait for a stable release. The big barrier I see is site rendering. Just getting the exercise pages would require an extra step, either manually generate `NB.HTML` and include as exercise files or add a `Makefile` like the DC/SWC template. Our modular assignment build gets more complicated as it uses the front matter in exercise markdown files to link and build from `_includes`. I'm not sure how we would accomplish combining `HTML` without front matter or building `NB.HTML` after combing `RMD`. We would definitely have to get dedicated and creative.

**Comment by ethanwhite** [comment]
I agree we would definitely want to wait until the notebooks were stable. Was thinking of this as a possibility for next year.

I also agree that it would be hard to get right. I was envisioning keeping the rest of the site working the same way and then automatically building the I agree that there would be a compile step at some point. Ideally we'd handle that using a continuous integration service, though that would make spinning up your own instance more complicated. Let's leave this open, but table it for now, since there's no point worrying about it until notebooks are stable. Once they get included in a release maybe we can set up some time for a video conference to talk through whether or not this is functionally obtainable given our modular approach to the course.

**Comment by ethanwhite** [comment]
Jupyter auto-grader: https://github.com/jupyter/nbgrader

**Comment by brymz** [comment]
It looks like this may be feasible after all!

The assignment page output I have been able to generate looks like:
 
![r-notebook-assignment](https://cloud.githubusercontent.com/assets/1743560/19776812/3a8121e0-9c3b-11e6-8b93-4629022249c3.jpg)

Students can access the `Rmd` source code through the `Code` button.

In addition to the migration of the exercise materials from `md` to `Rmd`, there will also have to be restructuring of the course site to rely on the file name of exercises. There is no front matter in the `nb.html` to draw from and the `Rmd` front matter is not accessed by Jekyll.

Cool idea! Lots of work to make happen across the site. My initial work is stored at https://github.com/brymz/datacarp-semester-biology/tree/notebooks

**Comment by brymz** [comment]
New RStudio Release with Notebooks: https://blog.rstudio.org/2016/11/01/announcing-rstudio-v1-0/

**Comment by ethanwhite** [comment]
Thanks for the great work exploring this @brymz. I think it's not at the top of the priority list at the moment so I'm going to close it for now. Anyone who finds this should feel free to reopen if interested in working on an implementation.
