### ISSUE TITLE
bad links?

### ISSUE THREAD

**Issue by lwasser** [datacarpentry/semester-biology#494]
Hello colleagues - I am running through the super awesome semester-biology materials and noticed 2 broken links here: http://www.datacarpentry.org/semester-biology/readings/R-fundamentals-1/ . Is this input of use to you or do you already know about these types of things? @brymz

**Comment by brymz** [comment]
Very helpful. Thanks, @lwasser!

**Comment by brymz** [comment]
Remove `.html` from readings links.

**Comment by lwasser** [comment]
Perfect. I’m enjoying the materials. Kudos to you and the team pulling them together and posting them here!

Leah

**Comment by brymz** [comment]
Glad to hear it! We appreciate any feedback.
