### ISSUE TITLE
Rerun dplyr output solutions

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#516]
dplyr seems to have made some minor changes recently that change the details of what the output looks like.

**Comment by brymz** [comment]
With the `dplyr` update, it looks like task 1 in ['Link to databases'](http://www.datacarpentry.org/semester-biology/exercises/Dplyr-link-to-databases-R/) returns `NA` unless you use `collect()`. ['Collect from databases'](http://www.datacarpentry.org/semester-biology/exercises/Dplyr-collect-from-databases-R/) is meant to get at that process. Do we:

* Drop task 1 from 'Link to databases'?
* Restructure the pair of assignments to introduce `collect()` from the beginning? *This would be like going back to the exercise structure before the split (#504).*

**Comment by ethanwhite** [comment]
I'm leaning towards "drop task 1" (and maybe replacing it with something else). What do you think?

**Comment by brymz** [comment]
> "drop task 1" (and maybe replacing it with something else)

OK. Any thoughts on the 'something else'? I think any replacement should be a simple operation to look at the structure of the `tbl`. I am not very familiar with those options. 

One option I found is to print out column names. It seems the equivalent of `names(surveys)` for the external table is `surveys$ops$vars`.

**Comment by ethanwhite** [comment]
No clear idea. I'm also OK with just dropping it.

**Comment by brymz** [comment]
Procedural Issue: 'Link to databases' has been significantly changed since the `after-fall2016` branch. I am not sure the best approach to make the fix.

* Change the old file and fix the merge conflict later. *This would act as some sort of flag, but will probably amount to more work later.* 
* Update the 'Link to Databases' file on `after-fall2016`, then make the changes. *I don't think I know how to do this.*
* Wait until after the semester to address this issue.

**Comment by ethanwhite** [comment]
The standard way to do this is probably to rebase the development branch. This would be something like:

```
git checkout after-fall2016
git rebase master
```

And fix the conflicts that occur along the way. This might be a lot of conflicts, but hopefully not too many.

**Comment by brymz** [comment]
Ha. Thanks. I'll give it a go when I get back to work in a couple of weeks.

**Comment by brymz** [comment]
> rebase the development branch

I tried and failed. The development branch `upstream/after-fall2016` is now in sync with `upstream/gh-pages`. It does not appear that the `after-fall2016` changes are present.

This is what I did:

```
zacharyrymsimac:datacarp-semester-biology Zack$ git checkout after-fall2016
Branch after-fall2016 set up to track remote branch after-fall2016 from upstream.
Switched to a new branch 'after-fall2016'
zacharyrymsimac:datacarp-semester-biology Zack$ git rebase gh-pages
First, rewinding head to replay your work on top of it...
Fast-forwarded after-fall2016 to gh-pages.
zacharyrymsimac:datacarp-semester-biology Zack$ git status
On branch after-fall2016
Your branch is ahead of 'upstream/after-fall2016' by 99 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
zacharyrymsimac:datacarp-semester-biology Zack$ git push upstream after-fall2016
To https://github.com/datacarpentry/semester-biology.git
 ! [rejected]        after-fall2016 -> after-fall2016 (fetch first)
error: failed to push some refs to 'https://github.com/datacarpentry/semester-biology.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
zacharyrymsimac:datacarp-semester-biology Zack$ git push -f upstream after-fall2016
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/datacarpentry/semester-biology.git
 + 1773bde...c545478 after-fall2016 -> after-fall2016 (forced update)
zacharyrymsimac:datacarp-semester-biology Zack$ git status
On branch after-fall2016
Your branch is up-to-date with 'upstream/after-fall2016'.
nothing to commit, working directory clean
```

Maybe I was supposed to `git push origin after-fall2016`? I am not sure how to get back the changes stored in `after-fall2016` before my unsuccessful `rebase`.

**Comment by ethanwhite** [comment]
It looks to me like your local copy of `after-fall2016` wasn't up to date when you did the rebase and then you overwrote the one on the remote with the `push -f`. Is there a reason your local repo wouldn't have been up to date? If this is it it's pretty hard to recover from. It may be able to be done with reflog, but it's tricky and it's extra truck since it's on a remote.

There is some indication we could get to the remote's reflog and reset this here:
http://stackoverflow.com/a/35273807/133513

**Comment by brymz** [comment]
I guess I'm having a hard time shifting the github workflow over to the 'remote' `after-fall2016`. I think it should be easy enough to start again with a fresh 'aftersemester' branch. There is only one PR that I will have to merge to get back on track. But, I want to be sure that I understand what I am doing before I dive into the remaining set of `aftersemester` issues.
