### ISSUE TITLE
Replace time-series examples in ggplot lecture

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#518]
The current ggplot lecture analyzes time-series data from Portal. This has a couple of disadvantages:
1. It requires some `dplyr` work up front. I'm not actually sure is this is good (review) or bad (extra time taken up before getting to graphing)
2. Portal is getting tired at this point, time to move on to something new
3. It's a fairly non-standard example of the kinds of bi-variate plots most folks will be used to making

**Comment by brymz** [comment]
How do you feel about the [Gapminder data](https://www.gapminder.org/data/)?

**Comment by ethanwhite** [comment]
I'd rather have something biological if possible. There might be something in there we could use on the disease side of things.

**Comment by brymz** [comment]
Could also continue with the BBS. Other ideas?

**Comment by ethanwhite** [comment]
BBS is tough to quickly get them up and running on. I was thinking about something that more naturally had two or more columns to plot against one another as well as different categories for demonstrating bar plots and histograms.

**Comment by brymz** [comment]
I found that the Andrews LTER Succession Plots Diameter Data fit nicely into the `ggplot` lecture. It also required some `dplyr` to `summarize()` the time series data, but I think that is a realistic process for datasets that biologists will encounter. The code example for the `ggplot` lecture using the Andrews data is https://gist.github.com/brymz/5dc254a6f3b998f9ea057d5a6b74b1ac

**Comment by brymz** [comment]
The idea is to replace the time-series analysis with something directly bi-variate using the Andrews Data.

**Comment by brymz** [comment]
Moving to some data that is directly bi-variate has me considering an introductory figure with `geom_point()` instead of `geom_line()`. Would you still want to introduce `geom_line()` somehow? Even if it means requiring data massaging?

**Comment by ethanwhite** [comment]
I don't think it's crucial, but I'm fine with including it if you have a decent example.
