### ISSUE TITLE
Check external links on `progbio`

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#520]

**Comment by brymz** [comment]
I used a free on-line link checker to find 83 broken links, but I can't figure out exactly where I'm supposed to be making the changes. 

What is he repo that builds http://www.programmingforbiologists.org/? 
* My initial thought was https://github.com/ethanwhite/progbio, but this repo seems to be incomplete. 
* Is it https://github.com/ethanwhite/my-awesome-course?

**Comment by ethanwhite** [comment]
> My initial thought was https://github.com/ethanwhite/progbio, but this repo seems to be incomplete.

That's the repo. Maybe you were looking at `master` and not `ghpages`?

**Comment by brymz** [comment]
That did it.
