### ISSUE TITLE
Introduce string in Making-choices-choice-operators-R

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#533]
http://www.datacarpentry.org/semester-biology/exercises/Making-choices-choice-operators-R/

Recent reordering means this comes before the initial introduction.

**Comment by brymz** [comment]
Can you be more specific of the change you would like to make?

**Comment by ethanwhite** [comment]
Sorry, typo, introduce `stingr`. We can probably grab the language from where we introduce it in loops.

**Comment by ethanwhite** [comment]
Given the really nice introduction to this in http://www.datacarpentry.org/semester-biology/exercises/Loops-stringr-R/ I'm now thinking maybe we should just remove these lines from this exercise entirely. Thoughts?
