### ISSUE TITLE
Replace, remove, or improve Strings-function-with-choices

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#541]
This question is a perennial source of confusion and it's a little weird to pass back a string like this anyway. We should be able to find something better for this kind of exercise.

**Comment by brymz** [comment]
I'm thinking of introducing a `lm()` or another stats function and printing out a report style `"r-squared = XXX"` or something similar. The choice could be a "significance" indicator like `"***"`.

**Comment by brymz** [comment]
The choice should return a value not a string. Return an r-squared `if()` significant.
