### ISSUE TITLE
`download.file` fails when knitting in knitr-examp.Rmd

### ISSUE THREAD

**Issue by davharris** [datacarpentry/semester-biology#544]
RStudio won't let me copy-paste the error message, but here's a screenshot. The upshot is "cannot open URL."  The same code works without issue if I run it from the console. No idea why it would behave differently in knitr.

![image](https://cloud.githubusercontent.com/assets/843017/19668116/64cb1b32-9a23-11e6-8b79-060e236d39c2.png)

**Comment by davharris** [comment]
Apparently, adding `method="curl"` to the download.file call fixes it on my machine. But I don't know if curl will work on Windows and linux machines without additional libraries...

**Comment by ethanwhite** [comment]
You're probably getting jammed up on a redirect since figshare changed how they handled files in the last year. Looks like the new link works fine:

https://ndownloader.figshare.com/files/2292172

PR in a change if you get the chance. Thanks.

**Comment by ethanwhite** [comment]
Also, here are are the Portal Project Teaching Database files if there are other broken links:

https://figshare.com/articles/Portal_Project_Teaching_Database/1314459

**Comment by davharris** [comment]
Thanks! Will PR.
