### ISSUE TITLE
knitr lesson technical issues

### ISSUE THREAD

**Issue by davharris** [datacarpentry/semester-biology#546]
The lesson went well, but we ran into a few technical hiccups:
- [x] Downloading RMarkdown through the knit button didn't "stick:" students had to `install.packages(rmarkdown)`
- [x] Many students don't have Pandoc/TeX installed; HTML worked more smoothly than PDF
- [x] The example code embedded in the .md file on the webpage should be updated to match the `knitr-examp.Rmd` file (ideally kept in sync automatically for the future)
- [x] The lesson doesn't currently make a clear distinction between the .R extension and the .Rmd extension, so some students were looking for a knit button above a .R file
- [x] The .Rpres and knitr-examp.Rmd files should be easier to find from the website

Also, the lesson still needs:
- [x] To deal with the suggestions @brymz made in #545

**Comment by brymz** [comment]
Are you going to get back to this @davharris? or is this on me?

**Comment by davharris** [comment]
If you have time to deal with it this week, that might be best.  Otherwise, I can definitely get to it eventually.

**Comment by brymz** [comment]
> example code embedded in the .md file on the webpage should be updated to match the knitr-examp.Rmd file (ideally kept in sync automatically for the future)

I wonder about using the `remote_file_content` plugin: https://github.com/dimitri-koenig/jekyll-plugins.

**Comment by brymz** [comment]
Also, we may consider updating this lecture for RStudio V1.0 with notebooks (#491).

**Comment by ethanwhite** [comment]
> example code embedded in the .md file on the webpage should be updated to match the knitr-examp.Rmd file (ideally kept in sync automatically for the future)

Is there are reason we need both of these files?

**Comment by ethanwhite** [comment]
> Also, we may consider updating this lecture for RStudio V1.0 with notebooks (#491).

Agreed, but probably a separate issue.

**Comment by brymz** [comment]
> > example code embedded in the .md file on the webpage should be updated to match the 
> > knitr-examp.Rmd file (ideally kept in sync automatically for the future)
>
> Is there are reason we need both of these files?

I think so. The `MD` is the lecture notes page, while the `Rmd` is the example item that the lecture is about. `.Rmd` are static files according to `jekyll` and won't be rendered into a web page. 

I have integrated material from the `Rpres` to the `MD` and removed the redundant `Rpres`.
