### ISSUE TITLE
Check solution to phenology from space

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#565]
I (and several students) get a subtly different graph.

We solved it this way (just the HARV data in the example):

```
library(raster)
library(dplyr)
ndvi_files = list.files("data/HARV_NDVI/",
                         full.names = TRUE,
                         pattern = "HARV_NDVI.*.tif")
ndvi_rasters <- stack(ndvi_files)
avg_ndvi <- cellStats(ndvi_rasters, mean)
avg_ndvi_df <- data.frame(samp_period = seq_along(avg_ndvi), ndvi = avg_ndvi)
ggplot(avg_ndvi_df, aes(x = samp_period, y = ndvi)) + geom_point()
```

**Comment by brymz** [comment]
It looks like the difference in solutions is that I used the `mean` of the `plot_locations` at each site instead of the `mean` of the whole raster image. The language is unclear in the exercise, so a revision could go either way.

**Comment by ethanwhite** [comment]
Ah, I see. What do you think about modifying it to include both as separate tasks. That way we can introduce `cellStats` but also reinforce extracting data for sites (and doing so repeatedly).

**Comment by brymz** [comment]
That's a great idea. Is that an `aftersemester` update? Do I update the output solution to your code for now?

**Comment by ethanwhite** [comment]
Yes and Yes.
