### ISSUE TITLE
Revised version of blog post for review

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#574]
Sorry this took *for ever*. Here's a revised version for you to look at:
https://github.com/datacarpentry/semester-biology/wiki/Data-Carpentry-for-Biologists:--Introductory-data-science-resources-and-course-website

**Comment by brymz** [comment]
Nice revision! The introduction you added was exactly what was missing. I went through and made some editorial changes for sentence structure and clarity. I also added some links. This should be pretty much ready to go.

**Comment by ethanwhite** [comment]
Thanks Zack. The changes look great. I did one more round of polishing and set this up to go live on Jabberwocky on Monday morning around 8:30 am. When you have time it would be good to write a couple of short posts for the Software Carpentry and Data Carpentry blogs pointing to the Jabberwocky post.

**Comment by ethanwhite** [comment]
Posted:
https://jabberwocky.weecology.org/2016/11/14/fork-our-course-a-semester-long-data-carpentry-course-for-biologists/

And getting lots of attention. Over 400 views so far.
