### ISSUE TITLE
Start list of courses using the site/materials/template

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#578]
Here's number 1:
* https://atredennick.github.io/ecology_class/

More in the pipes:
* https://twitter.com/atiretoo/status/798245407390199808

**Comment by brymz** [comment]
I also found https://palderman.github.io/IntroSciComp/. @palderman, can we list your course on our site?

It looks like a few folks have made a start. But, their pages have a similar lack of Hyde theme and I am unable to get past the home page. @potterzot, @mvevans89, are you having trouble customizing your course? How can we help?

*http://potterzot.com/semester-economics/
*https://mvevans89.github.io/ECOL-8030/

**Comment by mvevans89** [comment]
@brymz I'm pretty unfamiliar with Hyde and was having trouble getting it to render properly. If someone more experienced wants to take a look, that would be great! All I did was fork the repository, but before I could customize it, I couldn't manage to get the index page to load properly. Not sure if maybe there is something else I need to do?

**Comment by ethanwhite** [comment]
Hi @mvevans89 - thanks for giving this a try. As @brymz said we'll be happy to help figure out why this isn't working. In fact it's super useful to us to have some early adopters give things a try and help us figure out how they break. If you have a few minutes would you mind [opening a new issue](https://github.com/datacarpentry/semester-biology/issues/new) describing basically what you've said here so that we have a place to work through things and figure out what's going on? Thanks!

**Comment by palderman** [comment]
That's fine with me.  I'm thinking to rename the course "Data Carpentry for
Agriculture and Natural Resource Management" once I can rework the
assignments to be more ag and natural resource management focused.

Would that be a problem with respect to Data Carpentry branding?

-Phil

**Comment by ethanwhite** [comment]
@palderman - awesome. Thanks!

> Would that be a problem with respect to Data Carpentry branding?

That's a great question. I just opened an issue with the Data Carpentry board to talk about this and will get you an answer as soon as I can.

**Comment by ethanwhite** [comment]
Dropping this link here about another course that's going to use some of the Python exercises:
https://jabberwocky.weecology.org/2016/11/14/fork-our-course-a-semester-long-data-carpentry-course-for-biologists/#comment-30683
