### ISSUE TITLE
Add git example of deleting file and recovery

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#583]

**Comment by brymz** [comment]
I have managed to keep all of my git interaction on the command line up to this point and would not be able to thoughtfully contribute to this issue unless I take the time to learn the RStudio-git interface (*perhaps, that would be a good idea anyway if RStudio remains the best way to teach git to beginners*).

On the command line, recovering a deleted file is similar to the "Git as a time machine" section of the [lecture notes](http://www.datacarpentry.org/semester-biology/materials/version-control-R/) that introduces `revert`. My intuition says that this is not the case for a directory-based interface (*where does the deleted file go?*).

I don't have a specific question, just trying to get some more information to determine "what's next" for this issue.

**Comment by ethanwhite** [comment]
OK, no problem. Let's just leave this open and I'll get to it when I get to it.
