### ISSUE TITLE
forked websites not rendering

### ISSUE THREAD

**Issue by mvevans89** [datacarpentry/semester-biology#587]
newly forked repository does not load properly. the index page renders as basic HTML and none of the links work. see [https://mvevans89.github.io/ECOL-8030/](https://mvevans89.github.io/ECOL-8030/) for example

**Comment by brymz** [comment]
When I `cloned` the forked repo and ran a `bundle exec jekyll serve` to render the site on my local machine, everything worked ok. I noticed that the `_config.yml` file had not been updated and that would be my first recommendation for a fix. The `#Setup` section of your `_config.yml` should look something like:

```
# Setup
title:            Data Carpentry -for- Biologists
description:      'Teaching the tools to get computers to do cool science'
url:              http://mvevans89.github.io/ECOL-8030
baseurl:          /ECOL-8030
email:            datacarpentrysemester@weecology.org
feedbackurl:      https://docs.google.com/forms/d/e/1FAIpQLSdV_polFmoukgjcs1IC0Dd4iO1rdgwFnOds28xC_ma_z4tNIw
author:
  name:           'Michelle Evans'
  url:            https://twitter.com/ethanwhite

github:
  repo:           https://github.com/mvevans89/ECOL-8030
  #               Be sure the 'Issues' feature is activated in 'Settings'
```

**Comment by mvevans89** [comment]
@brymz Thanks, that did the trick! I'd updated the URL on github without updated it in the config file (doh!)

**Comment by brymz** [comment]
Glad that worked! Thanks for your interest in the project. Let us know if we can be any more help. 

We would be very excited to list your course as an example of a forked/customized version when you're up and running.

**Comment by ethanwhite** [comment]
Glad to see the two of you got this figured out.

@brymz - it might be worth opening an issue on the other repo showing the problem to let them know how to fix it.
