### ISSUE TITLE
New forks don't build unless some change is pushed.

### ISSUE THREAD

**Issue by humberto-ortiz** [datacarpentry/semester-biology#603]
I forked a copy of the course, and tried viewing the github pages version, but it didn build.

I contacted support and they said:

"Since you had never pushed to that repository after forking it, a Pages build wasn't started."

Update the documentation to suggest pushing a change before browsing the pages.

**Comment by brymz** [comment]
Thanks for the feedback, @humberto-ortiz! 

That first `push` should be updating the `#Setup` section in the `_config.yml` file. We'll be sure to revise the language there to make that more clear. 

We also recommend working with a local version of your repository. Once you  `clone` the repo locally and setup `jekyll`, you can run `bundle exec jekyll serve` to view the site at `http://localhost:4000` from a web browser.
