### ISSUE TITLE
Update `docs/`

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#606]
* add a note to the docs letting people know that if they are interested in using the "Data Carpentry" name that they should contact me

* add note to `contributing` about first `push` (#603)

**Comment by brymz** [comment]
@ethanwhite, Do we also want to update `LICENSE.md` to include a "Data Carpentry name" section?

**Comment by ethanwhite** [comment]
Yeah, that would be great.

**Comment by brymz** [comment]
@tracykteal, is there existing language for rights to the "Data Carpentry" name?
