### ISSUE TITLE
Update LICENSE to include "Data Carpentry" name use conditions

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#608]
@tracykteal and @jduckles, could you help with the language that we should use to clearly describe our expectations to instructors with forked/customized courses?

**Comment by ethanwhite** [comment]
Given that there isn't much of a policy here at this point I think something simple like:

> # Using the "Data Carpentry" trademark
>
> As detailed in the Instructional Material and Software sections, everyone is free to use the materials provided here for running courses as long as they provide attribution to the original source.
> 
> "Data Carpentry", the name, is a registered trademark. We are in the process of developing criteria under which a college/university course may use the "Data Carpentry" name (in the same way that there are [criteria for using the name for self-organized workshops](http://www.datacarpentry.org/self-organized-workshops/)). For now, if you are interested in including "Data Carpentry" in the name of your course please email Ethan White.
