### ISSUE TITLE
Rework SQL materials

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#614]
Based on a discussion with @ethanwhite...

- [x] split 'Introduction to databases' lecture (database management | relational databases)
- [x] revise lecture/assignment structure
    - intro week: 'demo code', 'intro to databases', 'tidy data', 'data entry'
    - queries week: 'basic queries', 'aggregation', 'joins'

**Comment by ethanwhite** [comment]
Yep, this sounds great. I've phrase the weeks as 'Entering & Storing Data' & 'Querying Data From a Database'.

The assignment restructure will then be Week 1: 'Improving Messy Data', 'Data entry validation in Excel', and 'Importing Data'; and everything else in Week 2.

**Comment by brymz** [comment]
While revising the lectures for "Database Queries", I noticed that a number of the exercises were not referenced to do in class (DISTINCT, Missing Data, GROUP BY, SUM, Detailed Join, Aggregated Join). Seems like content is presented for most of these exercises at some point during the lectures.
