### ISSUE TITLE
Fix broken website links

### ISSUE THREAD

**Issue by KristinaRiemer** [datacarpentry/semester-biology#624]
URLs for links in "Reading" Sections to Data Carpentry material have changed.

**Comment by ethanwhite** [comment]
Thanks for finding this @KristinaRiemer. This is definitely something we should take care of quickly. If you'd like to do it that's great, but if you can't get to it today let me know since I'd like to avoid the broken links sticking around any longer than necessary.

**Comment by KristinaRiemer** [comment]
I just now got the email notification for your message, I would have done it today if I'd known, sorry!

**Comment by ethanwhite** [comment]
No worries. Obviously I haven't gotten around to it yet either 😄

**Comment by ethanwhite** [comment]
Fixed in b2320a233f88f5984304b9bed1ec14deb677ee60. Thanks for reporting this @KristinaRiemer!
