### ISSUE TITLE
Add *very* detailed descriptions of exactly what to submit

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#634]

**Comment by KristinaRiemer** [comment]
What exactly do you mean by this? List the files they need to submit at the bottom of each week's assignment page?

**Comment by ethanwhite** [comment]
To be honest I wasn't sure when I wrote this. I answered a bunch of emails and canvas chats about what to submit for the SQL portion of the assignment and there were a number of cases where folks had managed to export tables and things from the SQLite database and tried submitting the resulting text files.

There are two ways to go. The first is the option you mention, which I kind of like since it puts the information directly with the assignment and allows it to be customized to specific weeks (like for this week noting that there should be a text file, an Excel file, and the SQLite file). The other option would be a general page describing what to do with an SQLite assignment and an R assignment.

**Comment by KristinaRiemer** [comment]
For the R weeks, do they generally turn in a single R script with all the problems in it, or one R script per problem? (Also which way is easier to grade, @andrewmarx?)

**Comment by ethanwhite** [comment]
One big script + associated data files in a zip is what we have done in the past. One script/problem would make it more difficult to build exercise to exercise and would also be a slower grading process for the decent fraction of folks who do everything perfectly.

**Comment by KristinaRiemer** [comment]
Seems like your second option, a general page on what to turn in for SQL and R weeks, would work. Unless I'm overlooking something, the first week's assignment is the only one with multiple file formats to turn in. I think I could probably at least attempt to add this.

**Comment by ethanwhite** [comment]
Sounds good to me. Go for it!

**Comment by KristinaRiemer** [comment]
See #635

**Comment by ethanwhite** [comment]
Fixed in #635. Thanks @KristinaRiemer!
