### ISSUE TITLE
Expand netiquette section of syllabus

### ISSUE THREAD

**Issue by KristinaRiemer** [datacarpentry/semester-biology#636]
"Rules of common courtesy" seems really vague, though maybe that's intentional (due to university rules or something)? If it's not, maybe there are websites with codes of conduct out there that we could link to in this section, to make expectations of appropriate behavior more clear.

**Comment by ethanwhite** [comment]
This is UF boilerplate that I believe we're required to include as is, but I wouldn't have spent much time looking in to it so you're welcome to discuss it with Claire if you're interested in doing more. Using things other than boilerplate in these areas is likely to involve a fairly large number of discussions and emails. That doesn't mean it's not worth it but you should be aware that it will likely be a meaningful investment of time having awkward conversations with bureaucrats.

**Comment by KristinaRiemer** [comment]
Okay, I thought that might be the case. I've never even heard of "netiquette" before, but all it took was a quick Google search to understand, so if students are interested or want to make sure they're not breaking any rules, they can do the same. I don't really think it's worth further time right now.

**Comment by ethanwhite** [comment]
> I've never even heard of "netiquette" before

That words was one of the ways I knew it was boilerplate, because I wouldn't have used it or merged it :smile:
