### ISSUE TITLE
Include link to turn in checklist on each page

### ISSUE THREAD

**Issue by andrewmarx** [datacarpentry/semester-biology#642]
I was wondering if it would be worthwhile to include a link to the turn in checklist at the end of each assignment so that as the students finish the last problem they are reminded to go through it.

**Comment by KristinaRiemer** [comment]
I added a link to the checklist page at the top of the "Assignment Schedule" page in #635, but I also like this idea.

**Comment by ethanwhite** [comment]
In concept we can do this. It involves making a copy of this page in `_includes` and adding that include to the assignment pages after the reading and assignment includes. I won't have time to get to this this week (except maybe while @KristinaRiemer is teaching), but I think it's a fine idea and either of you are welcome to implement it.

**Comment by andrewmarx** [comment]
I have it working in my fork just by adding a link to the end of `_includes/assignment.html`

Is this an acceptable approach? Or does it violate some design principles?

**Comment by ethanwhite** [comment]
That's exactly where I would have put it. Go ahead and submit a PR and I'll take a look at the details.

**Comment by ethanwhite** [comment]
Implemented in #844. Thanks @andrewmarx!
