### ISSUE TITLE
Rearrange intro R lecture materials

### ISSUE THREAD

**Issue by KristinaRiemer** [datacarpentry/semester-biology#647]
New proposed order, with new content italicized. 

* Introduction to R
  * R/RStudio
  * _Create Week 3 folder_
  * Basic expressions
    * _During, create new R script & save as notes.R in new folder_
  * Rest of section
    * _They should save assignment R script in new folder_

* Data structures
  * Vectors
  * Matrices
  * Projects
    * _"Who's ever had problems with working directories?"_
    * _Existing directory = Week 3 folder_
    * _Will see how projects are helpful soon_
  * Data frames
  * Importing data
    * _Create data subdirectory_
    * _Using relative instead of absolute paths (no setwd())_
  * _Zip week 3 folder to turn in_

@ethanwhite does this seem about right?

**Comment by ethanwhite** [comment]
Looks great.

**Comment by KristinaRiemer** [comment]
@ethanwhite, when introducing projects, should we explicitly mention the .Rproj file or have students not noticed it if it's not pointed out?

**Comment by ethanwhite** [comment]
Yes, let's go ahead and mention it and provide a short description of what it is and isn't. This will avoid confusion like thinking the entire project is inside the Rproj file.

**Comment by KristinaRiemer** [comment]
Done with b785c82d
