### ISSUE TITLE
Possible changes to dplyr lecture material

### ISSUE THREAD

**Issue by KristinaRiemer** [datacarpentry/semester-biology#654]
These things shouldn't be done until later in the semester/after the semester. 

* Replace aggregation na.rm with removing nulls (i.e., `filter(!is.na(column_name))`)
* Add installation of RSQLite package at beginning of SQL section
    * Or maybe make SQL section optional/remove/just a demo (but people will try to follow along)? 
* Maybe use only two functions instead of three when introducing pipes to make the example a little simpler? 
    * Start with pipe to one function, then assign output to new variable name, then add on a second function
* Add note about warnings vs errors after inner_join code (because this throws a warning)
* #653

**Comment by ethanwhite** [comment]
All of these that are still relevant are now implemented.
