### ISSUE TITLE
Create datasets page

### ISSUE THREAD

**Issue by KristinaRiemer** [datacarpentry/semester-biology#666]
A central place to store URLs for all the datasets used, to make it easier for students to find the URLs quickly during class. Link to on main page, assignment schedule page, and lecture pages where datasets are described/read in.

**Comment by KristinaRiemer** [comment]
I wonder if there'd be a way to explicitly link the URL on the datasets page to the references to the URLs in the lecture notes, so that when the links change we can just change the datasets page URLs?

**Comment by ethanwhite** [comment]
That is possible. We would basically create a bunch of variables that hold dataset urls and then reference those variables instead of the urls themselves.

**Comment by ethanwhite** [comment]
@KristinaRiemer created the datasets page. No work yet on centralizing the URL storage. I'm going to go ahead and close this one since the core task has been handled, but if someone wants to work on some centralization around datasets/urls I think that would be great.
