### ISSUE TITLE
Spatial data material: new possible exercise

### ISSUE THREAD

**Issue by KristinaRiemer** [datacarpentry/semester-biology#698]
Pull in bioclim climate data using `getData()` and make a scatterplot of two chosen bioclim variables to represent the possible climate space. Then pull in species occurrence data, extract their bioclim values, and plot them on top of the bioclim points in a different color to see what part of the climate space they're occupying. 

To incorporate some `dplyr`, include some sort of filtering/mutating/etc. of the occurrence data.

**Comment by ethanwhite** [comment]
This would be a good integrative problem to be added to the end of the semester.

**Comment by ethanwhite** [comment]
Let's make this one of the first "mini projects" that we do. It can go in Week 6.

**Comment by ethanwhite** [comment]
Implemented in 5ec1f356a0aff9f0ff5cd7556735664e0c0878c4 and follow up edits. Thanks @KristinaRiemer!
