### ISSUE TITLE
Should we drop floating point in conditionals lecture

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#708]
Extra complexity that most students aren't ready for yet. Takes time away from discussing and practicing core idea.

**Comment by ethanwhite** [comment]
Any thoughts on this @KristinaRiemer & @brymz?

**Comment by brymz** [comment]
Is there another time in the semester that floating point are introduced? The shift between integer and float was an 'ah-ha' moment in understanding computers I still remember.

**Comment by ethanwhite** [comment]
No, not right now. Interesting to hear that it was a real 'ah-ha' moment. Maybe I'll go ahead and keep it in this year and make sure to carefully think about how it goes.

**Comment by KristinaRiemer** [comment]
@ethanwhite I don't remember what the problem with this was? I think I might not have been there that week. I still think it's important to include because it can easily cause problems, and I don't know where else it would fit in.

**Comment by ethanwhite** [comment]
OK, thanks. Closing this. Will leave it in this year and adjust as necessary.
