### ISSUE TITLE
Are you interested in using The Carpentries GitHub labels?

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/semester-biology#736]
The Carpentries have developed a series of [standard GitHub labels](http://www.datacarpentry.org/2018-04-05-github-labels) to use across our repositories. The list of labels is available in The Carpentries [handbook](https://docs.carpentries.org/topic_folders/maintainers/github_labels.html). Would you be interested in using them for this repository as well?

**Comment by ethanwhite** [comment]
Yes, we'd be happy to switch over the standard labels. Would you like me to add you as a collaborator so that you can implement?

**Comment by fmichonneau** [comment]
Given that I have admin level access within the organization, I can already update the labels. So if you are ready, I'd be happy to deploy them. What would you like me to do with the old labels? I can leave them as is, delete them all, or do something in between. Thanks!

**Comment by ethanwhite** [comment]
Go for it! Leave the old labels in place for now.

**Comment by fmichonneau** [comment]
The new labels are now deployed. Thanks! Let us know how they work for you.
