### ISSUE TITLE
Fix class feedback system

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#740]
Inconsistent display of needed information on Linux.

**Comment by KristinaRiemer** [comment]
What is this? I vaguely remember having problems with the system at the end of the semester.

**Comment by ethanwhite** [comment]
Yeah, there was something about the polling system that wasn't showing up at least on my linux laptop a bunch. That's all I remember at this point, which is why I just jotted it down. The link to the form itself is here:

http://datacarpentry.org/semester-biology/in-class-feedback/

**Comment by ethanwhite** [comment]
Done
