### ISSUE TITLE
Switch over from SQLite Manager to DB Browser for SQLite

### ISSUE THREAD

**Issue by KristinaRiemer** [datacarpentry/semester-biology#745]
The Data Carpentry Ecology lessons now use DB Browser because SQLite Manager is no longer being maintained. I'm not sure what, if anything, from the semester course lesson would need to be changed to accommodate this. If that seems like a good idea @ethanwhite, I can do it. Otherwise feel free to close this issue.

**Comment by ethanwhite** [comment]
Yes, we should switch over the DB Browser. I think it's mostly just changing descriptions of the interface which are definitely in the lecture and probably in one or two of the exercises as well.

I am planning on moving the databases material later in the semester to just hit R right away, but any fixes for this should be independent of that change. Thanks!

**Comment by ethanwhite** [comment]
We did this at some point last fall.
