### ISSUE TITLE
Broken link check

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#746]
Run a broken link checker since some of the reading materials have almost certainly shifted locations.

**Comment by fmichonneau** [comment]
Running the following on a fresh checkout of the repo, and after running `bundle exec jekyll build`

```
linkchecker --file-output=csv/tmp/link_res.log _site
```

Results in :

[link_res.log](https://github.com/datacarpentry/semester-biology/files/2290463/link_res.log)

**Comment by ethanwhite** [comment]
Thanks @fmichonneau. I just fixed those in ae1aa8b.

There are also the following external links:

404 Not Found | https://datacarpentry.org/atom.xml | link/href [301 from http://datacarpentry.org/atom.xml]
-- | -- | --
404 Not Found | https://assessment.aa.ufl.edu/Data/Sites/22/media/2013-14gaap/cals/2013-14-cals-wildlife-ecol-and-consvn-phd-aap.pdf | Ph.D.  and MS in Wildlife Ecology and Conservation Academic Assessment Plans  [301 from  http://assessment.aa.ufl.edu/Data/Sites/22/media/2013-14gaap/cals/2013-14-cals-wildlife-ecol-and-consvn-phd-aap.pdf]
404 Not Found | http://neondataskills.org/tutorial-series/raster-data-series/ | NEON Raster Tutorial
404 Not Found | http://neondataskills.org/tutorial-series/vector-data-series/ | NEON Vector Tutorial
404 Not Found | http://neondataskills.org/self-paced-tutorial/1_About-LiDAR-Data-Light-Detection-and-Ranging_Activity1/ | LiDAR
404 Not Found | http://neondataskills.org/R/Raster-Calculations-In-R/ | Canopy Height Models
403 Forbidden | http://www.jstor.org/stable/4524171 | Seebacher 2001
404 Not Found | https://cran.rstudio.com/web/packages/dplyr/vignettes/databases.html | dplyr databases
404 Not Found | https://www.neonscience.org/data-resources/get-data/airborne-data | high-resolution airborne imaging [301 from http://www.neonscience.org/data-resources/get-data/airborne-data]
404 Not Found | https://datacarpentry.org/sql-ecology-lesson/03-sql-joins-aliases | Reading [301 from http://www.datacarpentry.org/sql-ecology-lesson/03-sql-joins-aliases]
-1 Not found: The server name or address could not be resolved | http://www.expressivecode.org/2014/12/17/mutating-using-functions-in-dplyr/ | here’s an example
404 Not Found | https://www.w3schools.com/sql/sql_drop.asp | DROP TABLE [301 from http://www.w3schools.com/sql/sql_drop.asp]
404 Not Found | http://neondataskills.org/lidar-data/lidar-data-rasters-in-R/ | tutorial for raster data
-1 Not found: The server name or address could not be resolved | http://www.neonhighered.org/Data/LidarActivity/CHM_InSitu_Data.zip | LiDAR Dataset
404 Not Found | http://swcarpentry.github.io/r-novice-inflammation/reference/ | R Reference
404 Not Found | https://uc3.cdlib.org/2014/04/10/abandon-all-hope-ye-who-enter-dates-in-excel/ | https://datapub.cdlib.org/2014/04/10/abandon-all-hope-ye-who-enter-dates-in-excel/  [301 from  https://datapub.cdlib.org/2014/04/10/abandon-all-hope-ye-who-enter-dates-in-excel/]
404 Not Found | http://stat.ethz.ch/R-manual/R-devel/library/statistics/html | statistics functions
404 Not Found | https://datacarpentry.org/R-ecology-lesson/01-intro-to-R.html | Introduction to R [301 from http://www.datacarpentry.org/R-ecology-lesson/01-intro-to-R.html]
404 Not Found | https://scipy.org/download.html | Download page for Numpy &amp; Scipy [301 from http://new.scipy.org/download.html]
404 Not Found | https://pythonhosted.org/DendroPy/index.html | DendroPy [301 from http://packages.python.org/DendroPy/index.html] [301 from https://packages.python.org/DendroPy/index.html]
404 Not Found | https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml | Google
403 Forbidden | http://www.jstor.org/stable/25145087 | like this
404 Not Found | https://www.pasteur.fr/fr/formation/infobio/python | Programming  Course for Biologists at the Pasteur Institute [301 from  http://www.pasteur.fr/formation/infobio/python/] [301 from  https://www.pasteur.fr/formation/infobio/python/]
404 Not Found | https://www.pasteur.fr/fr/recherche/unites/sis/formation/python/index.html | Python  course in bioinformatics at the Pasteur Institute [301 from  http://www.pasteur.fr/recherche/unites/sis/formation/python/index.html]  [301 from  https://www.pasteur.fr/recherche/unites/sis/formation/python/index.html]
404 Not Found | https://github.com/datacarpentry/semester-biology/settings | your repository Settings tab
404 Not Found | https://palderman.github.io/IntroSciComp/ | Introduction to Scientific Computing
404 Not Found | https://github.com/datacarpentry/semester-biology/blob/master/docs/contributing.md | contributing.md
404 Not Found | https://datacarpentry.org/favicon-dc.ico | link/href [301 from http://datacarpentry.org/favicon-dc.ico]
-1 Timeout | http://numpy.scipy.org/ | Numpy
Too many redirections | https://www.wikispaces.com/ | British  Library Labs Teaching and Learning Award [302 from  http://labs.bl.uk/British+Library+Labs+Awards] [302 from  https://session.wikispaces.com/1/auth/auth?authToken=ea08a752d06391f7d9f98493ef260a08]  [302 from https://www.wikispaces.com/] [302 from  https://session.wikispaces.com/1/auth/auth?authToken=228248d9d96b91f181aeb6e07e83a7a9]  [302 from https://www.wikispaces.com/] [302 from  https://session.wikispaces.com/1/auth/auth?authToken=7d1ef7a5b2baa3842b32e7ad86aebb35]  [302 from https://www.wikispaces.com/] [302 from  https://session.wikispaces.com/1/auth/auth?authToken=3dccb6047004f4e7025917297dbbcc7a]  [302 from https://www.wikispaces.com/] [302 from  https://session.wikispaces.com/1/auth/auth?authToken=f5a90f7f6ebdcd8906665d50de5b03d1]
404 Not Found | http://datacarpentry.org/semester-biology/materials/running-blast-from-pythons | Running Blast
404 Not Found | http://datacarpentry.org/semester-biology/data/PortalMammals_plots.csv | Plots table
404 Not Found | http://datacarpentry.org/semester-biology/data/PortalMammals_species.csv | Species table
404 Not Found | http://datacarpentry.org/sql-ecology-lesson/setup/ | Setup
-1 Timeout | http://datacarpentry.org/semester-biology/data/NEON-airborne.zip | Download
-1 Timeout | http://datacarpentry.org/semester-biology/data/HARV-NDVI.zip | HARV_NDVI
-1 Timeout | http://datacarpentry.org/semester-biology/data/SJER-NDVI.zip | SJER_NDVI
