### ISSUE TITLE
Create a data or spreadsheet language

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#755]
Some topics really are just about data related things, not SQL. Either rename to "spreadsheets" or the like or just use "Data"

**Comment by KristinaRiemer** [comment]
What about changing "Language" to "Topic", and including "Data management" along with R, SQL, etc.? Would this just have to be changed in the xx-template.md files?

**Comment by ethanwhite** [comment]
I like that, though we'll have to see what something that long does to the layout of http://datacarpentry.org/semester-biology/schedule/. I think "data" might work if the longer form is problematic. It should be changed in the template files, but also anywhere else that variable gets used. E.g., on the schedule page and lecture materials page, etc.

**Comment by KristinaRiemer** [comment]
I'll take a crack at it.

**Comment by ethanwhite** [comment]
Awesome. Thanks!

**Comment by KristinaRiemer** [comment]
"Topic" is already being used as part of the yaml, so I'm going to use "Focus" instead.

**Comment by ethanwhite** [comment]
It also looks like `Topic` is barely used. From a quick glance it looks like it might just be used an as extra level of title on the individual exercise pages. If that's the case then we could just replace the current usage. The current use of `Topic` is potentially usefuI for selecting exercises to swap in and out, which would argue for keeping it, but I'm a little concerned that `Focus` is a pretty nebulous term. So, no strong opinions here, just throughts.

**Comment by KristinaRiemer** [comment]
Yeah, I also think that the term "Focus" is too vague, but couldn't think of anything better. I can co-op "Topic" if you're okay with that?

**Comment by KristinaRiemer** [comment]
I also still don't really understand how the website is structured. I tried to just replace as many instances of "Language" with "Topic" as I could find in the template and materials/exercises .md files. Is there a particular high-level file that that should be changed in?

**Comment by ethanwhite** [comment]
Yeah, most of sites underlying mechanics occurs in the files in the `_includes` and `_layouts` directories.

**Comment by ethanwhite** [comment]
Happy to chat more about what's going on there after you take a look if that would be useful.
