### ISSUE TITLE
Missing solutions for Species Occurrences Elevation Histogram

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#768]
There is currently no link on the website. I haven't checked yet to see if the solutions are there and not linking or not present.

**Comment by KristinaRiemer** [comment]
I forgot to add the new file during the commit for that exercise, I'll get it in with a PR in a second.

**Comment by KristinaRiemer** [comment]
See #769

**Comment by KristinaRiemer** [comment]
Fixed with b8612454e
