### ISSUE TITLE
Use ggspatial for spatial data plotting with ggplot

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#812]
https://github.com/paleolimbot/ggspatial

**Comment by KristinaRiemer** [comment]
It looks like this avoids having to convert spatial objects to dataframes before plotting?

**Comment by ethanwhite** [comment]
Yep, which I think would really simplify that material in a useful way. There was a lot of tripping over if/when to convert things to data frames, so just leaving rasters as rasters should be a big improvement.

**Comment by ethanwhite** [comment]
Carpentries has now reversed course on this change and having spent some time working on writing the lecture I understand why. The different interface, which is really intuitive on it's own, results in insufficient conceptual overlap with the lessons from regular `ggplot`, so instead of building up and revisiting these concepts we basically end up introducing a new way to plotting things that still starts with `ggplot()`. So, I'm going to maintain the current approach using core `ggplot` for now. If someone else wants to develop another version of the material for ggspatial I'd be happy to include it.
