### ISSUE TITLE
Potential teaching topic: creating production quality images

### ISSUE THREAD

**Issue by andrewmarx** [datacarpentry/semester-biology#820]
One potential topic for the class is creating figures for manuscripts, posters, webpages, etc. This is something that virtually anyone taking the class could benefit from. Some key things that could be covered:
- File formats: jpeg vs png vs vector formats (I'd pick a specific vector format, but they all have inconsistent support). For example, jpeg is lossy, but good for photos. png is better for figures with things like lines and text.
- Resolution/dpi: Anything for print (manuscript/poster) should probably be at least 300dpi, whereas web content dpi can generally be much lower.
- Image dimensions: For print especially, the dimensions of the image should be accounted for when exporting figures.
- Color palettes: Being aware of how an image looks in grayscale and with different forms of colorblindness. Grayscale is especially important so that if readers print off something without color, they can still interpret the figures. The viridis package would be good here.
- Color theory: maybe a little background on pairing colors (addressing things like contrast)? just to make sure people are aware why some colors should never be paired. [Colored text](https://www.lifewire.com/thmb/WWxsqFDVhpbUj1-J58P6gxuPQ80=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/Color-Contrast-Chart-59091b973df78c9283e31928.jpg) is an obvious use case

**Comment by ethanwhite** [comment]
I really like the idea of spending some more time on the more advanced aspects of data vis and I think this is something good to cover in the space. When planning next week let's think about adding this as a day in towards the end of the semester.

**Comment by ethanwhite** [comment]
OK, I'm sold. I think this is a great idea. It turns out that the Friday of Week 7 is a holiday and so we need something we can cover in one day. I think we can do this with this material, so I'm planning on adding it then.

**Comment by ethanwhite** [comment]
Opened a new issue to work on this so closing this one.
