### ISSUE TITLE
Consider 3 Intro + dplyr weeks next year

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#845]
Weeks 2-3 are currently a bit short for the material for novices. The challenge is that stretching this material to 2-4 is a bit long. Here's one stretch, but then what to do on the 3rd Friday?

Week 1: Course intro + data structure
Week 2: Basic intro to R. No assignment. Feel free to skip if you know it all.
Week 3: T (Paths, Basic reproducibility), R (dplyr: select, filter, mutate, arrange, adv filter aggregation)
Week 4: T (dplyr: joins), F ?

We've gone back and forth on this historically for exactly this reason

**Comment by andrewmarx** [comment]
My thoughts after the last semester were that week 2 should be split into 2 weeks, such that week 2 would not cover data frames, only vectors, which could allow for more detailed explanations and more practice with manipulating vectors. Then week 3 would be about data frames and extending what they learned about manipulating vectors to data frames. This extra practice for both would hopefully help get people more comfortable with vectors and data frames before moving on, which is important because they are used extensively throughout the course. Many issues people have later in the semester come back to these more fundamental topics rather than the new topic at hand, which hinders their ability to learn and apply the new topic

**Comment by ethanwhite** [comment]
Thanks @andrewmarx. Are you envisioning new material or just spreading out the existing material? If new material then given the shift to online (plus other COVID related losses of time) I'm not sure I have time to develop new stuff for the beginning of the semester. If you have time to develop the material yourself I'd be happy to chat about it.

If you're basically envisioning slowing down the current material I'm certainly open to that discussion, and the question is what exactly would that look like.

Week 2: Intro to R & RStudio + Vectors (I agree that this is a good amount of material for beginners)
Week 3: Data frames + Basic dplyr (select, filter, mutate, arrange). This allows more time for doing advanced filtering (detailed discussion of `and` and `or`, proper treatment of `NA`s).
Week 4: Joins + ?. Joins doesn't seem like enough for a full week. I could see it along with a bunch of review exercises, but then someone needs to find the time to develop them.

This + the loss of a week due to the late start date would require dropping teaching version control, which I'm open to. It would also mean that the first week of iteration is separated from the 2nd week by the Thanksgiving holiday and if we lose a week to a hurricane we'd end up dropping loops entirely.

**Comment by ethanwhite** [comment]
OK, here's a possible version of the semester with the proposed extension:

1. Data Entry & Storage
2. Intro to R & RStudio (vectors, but no data frames)
3. Data frames + Basic dplyr 
4. Joins + maybe some work on combining/assembling/disassembling data frames
5. (Tuesday only) Basic reproducibility + some material from "bigger problems"
6. Data Vis
7. Spatial 1 (we also talked about splitting this last year to give us more time)
8. Spatial 2
9. Functions
10. Conditionals
11. Repetition 1
12. Repetition 2
13. (Thanksgiving week, Tuesday only) tidyr/knitr/bigger problems
14. Version control or databases
15. (Tuesday only) tidyr/knitr/bigger problems

We lose the "Bigger Problems" week, but I think that's doable and unavoidable since I can't see splitting repetition into before and after the Thanksgiving holiday. We would move any of the useful lecture material from that into the Week 5 half week, which would basically just be videos to watch with no assignment.

**Comment by ethanwhite** [comment]
In the process of implementing the structure described above.

**Comment by ethanwhite** [comment]
This has been implemented as part of the 2020 course.
