### ISSUE TITLE
Providing library imports at top of assigments

### ISSUE THREAD

**Issue by andrewmarx** [datacarpentry/semester-biology#888]
I'm proposing that at the top of each assignment we provide a copy/paste code block for students that includes all the needed libraries for that particular assignment. What this would accomplish:
1. Encourages students to load libraries in a single location at the top of the file. We encourage this behavior but do not enforce it, leading to people having library imports throughout the document, and sometimes students load the same library repeatedly.
1. Ensures that students are clear about what libraries are needed for the entire assignment. Otherwise, if a student isn't sure about libraries they should be using, this can lead to them wasting time trying to figure out what they need.
1. Ensures that packages are loaded in the correct order for assignments where multiple packages have functions with the same names. This is a frequent issue; every year multiple students inadvertently override functions midway through an assignment, and it causes reproducibility issues for both them and the instructors. This could also be the source of an optional exercise, where the student is instructed to switch the order that libraries are loaded, the session is cleared, then everything is rerun. They would then describe what occurred and why as a comment, then fix the library order for submission
1. Prevents students from loading unnecessary packages. For example, while dplyr and tidyr can be installed and loaded individually, some students have submitted answers that load the entire tidyverse package, which does not necessary break things, but can slow down grading. In cases where there are multiple ways to approach a problem, it helps to ensure that students use the approach that results in output that matches the given output. This is potentially an issue when loading csv files using secondary packages that might change things like the order of records.

An example of what the code block might look like:
```
# Load the necessary libraries for the assignment
library(raster)
library(dplyr)

```

**Comment by ethanwhite** [comment]
I think this is a really good idea @andrewmarx. I just pushed an example to https://datacarpentry.org/semester-biology/assignments/r-intro/ Let me know what you think.

**Comment by ethanwhite** [comment]
Oops, wrong link: https://datacarpentry.org/semester-biology/assignments/r-data/

**Comment by andrewmarx** [comment]
Looks good

**Comment by ethanwhite** [comment]
Great. I'll try to remember to add these each week, but feel free to remind me if I miss one.
