### ISSUE TITLE
Neon-harvard-forest-soils-analysis-R.md part 2 output issue

### ISSUE THREAD

**Issue by andrewmarx** [datacarpentry/semester-biology#899]
Part 2 of the first exercise for week 8 is not colored correctly

I'm not sure the proper way to generate outputs, so I'll leave it to you

**Comment by ethanwhite** [comment]
Thanks! Good catch. I think that's a copy paste error because I don't think it makes sense to color differently. I removed the reference to a color map.

Fixed in a53f29bf9614a24a78bd612a29cdb923aa5b196d.
