### ISSUE TITLE
Change data file names to lower case

### ISSUE THREAD

**Issue by andrewmarx** [datacarpentry/semester-biology#902]
The data files for some assignments, particularly the spatial sections, have file names with mixed case. This sometimes causes issues with grading on a Linux machine because most students use OS's where capitalization in file paths does not matter, so they sometimes mistype the name in such a way where it works for them but not others. More subjectively, I think this change would also just reflect better practices in the materials, but that's obviously a debatable topic.

**Comment by ethanwhite** [comment]
I think this is a good idea.
