### ISSUE TITLE
Preparing to submit Data Carpentry Semester Biology to the Journal of Open Source Education

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#907]
Hi everyone - I'm planning to submit this course to the [Journal of Open Source Education](https://jose.theoj.org/about) in the next couple of months. The material is increasingly widely used and I think the folks who have actively contributed in a variety of roles over the years deserve some much earned credit for their contributions to this valued open educational resource.

An initial look through the commit log, issue queue, and my brain suggests that at least the following folks should be included as authors on this publication:

- [x] myself
- [x] @brymz
- [x] @andrewmarx
- [x] @KristinaRiemer
- [x] @MarconiS
- [x] @davharris
- [x] @garezana 
- [x] @skmorgane

Everyone on this list has contributed significantly in areas including material development, material review & feedback, teaching in the course (and providing active feedback while doing so), producing data for exercises, and big picture planning and design. Please indicate your agreement with being involved in a response below, let me know if you want to review the short summary of the course I need to write for JOSE before I submit, and provide the following information:

```
 - name: Ethan White
 - affiliation: Department of Wildlife Ecology and Conservation, University of Florida
 - orcid: 0000-0001-6728-7745
```
I'm happy to chat with anyone who has questions about if they deserve authorship, but I am personally convinced that all of you do.

To anyone not on this list who has made a meaningful contribution to the project please let me know. This effort has been around in one form or another for over a decade and it is easy to lose track of significant contributions that don't show up in the places that are easy to check.

Right now the To Do list for getting things submitted is:

- [x] Finish reviewing captions for the new video component of the course (I'm about 90% of the way through)
- [x] Write the (short) manuscript describing the project
- [x] Release current version of course on GitHub
- [x] Archive current version of course to Zenodo
- [x] Author sign-offs
    - [x] myself
    - [x] @brymz
    - [x] @andrewmarx
    - [x] @KristinaRiemer
    - [x] @MarconiS
    - [x] @davharris
    - [x] @garezana 
    - [x] @skmorgane
- [x] Submit

I will ping this issue as things progress. Let me know if you have any questions.

**Comment by ethanwhite** [comment]
P.S. - I just checked and the course site has now been viewed over 300,000 times!

**Comment by davharris** [comment]
Thanks Ethan!

Name: David Jay Harris
Orcid: 0000-0003-3332-9307
Affiliation: Probably UF? I don’t see a reason to mention Chewy

I’ll waive the option to review the paper before submission, if that’s okay.

Thanks again! Hope you’re all doing well

Dave

**Comment by KristinaRiemer** [comment]
This seems like a great idea! I'd be happy to review anything that you would like feedback on. 

 - name: Kristina Riemer
 - affiliation: College of Agriculture and Life Sciences, University of Arizona
 - orcid: 0000-0003-3802-3331

**Comment by MarconiS** [comment]
Thanks @ethanwhite!

Name: Sergio Marconi
Orcid: 0000-0002-8096-754X
Affiliation: School of Forest Resources & Conservation, University of Florida

Happy to contribute to any point of the ToDo list.

Take care you all!

**Comment by brymz** [comment]
I'm in!

 - name: Zachary T. Brym
 - affiliation: Tropical Research and Education Center, Department of Agronomy, UF/IFAS
 - orcid: 0000-0002-0659-2938

I can also acknowledge my spin-off of the course platform: [Introducing Agroecology](https://trec-agroecology.github.io/introducing-agroecology/)

Also, how do you go about tracking those page views? My bosses want to know.

**Comment by andrewmarx** [comment]
- name: Andrew J. Marx
- affiliation: Department of Wildlife Ecology and Conservation, University of Florida
- orcid: 0000-0002-7456-1631

**Comment by garezana** [comment]
name: Virnaliz Cruz
affiliation: School of Natural Resources and Environment, University of Florida
orcid: 0000-0001-6783-2651

**Comment by ethanwhite** [comment]
I've finally finished doing the rest of the manual captioning fixes, which was the big task to do before proceeding. I've gone ahead and released and archived the current version of the course.

The big thing left to do now is write the paper. I've created a stub for the paper on Google Docs: https://docs.google.com/document/d/1-3eXqHs3Q9GOEHg5Hnvu12-kE_nAm1AzYxPipsie6DY/edit?usp=sharing

It currently only contains a title, the author line, and the acknowledgements. I'll try to put together a short outline and then anyone who wants to do some writing is welcome to jump in and help out.

**Comment by ethanwhite** [comment]
About 6 months later than expected I think we're basically ready to go for submission. If @andrewmarx @brymz @KristinaRiemer @garezana & @skmorgane can all take a look at the ms:

https://docs.google.com/document/d/1-3eXqHs3Q9GOEHg5Hnvu12-kE_nAm1AzYxPipsie6DY/edit

make any edits (in Suggesting mode) that you think are appropriate, and sign-off on submission, then I can start working on (finally) getting this out the door.

**Comment by ethanwhite** [comment]
@davharris - I'm counting you as having signed off already based on:

> I’ll waive the option to review the paper before submission, if that’s okay.

But let me know if that's changed.

**Comment by brymz** [comment]
Thanks, @ethanwhite. Nice to see it come together!
I've got the review on my list for this week or early next.

**Comment by KristinaRiemer** [comment]
I added some comments and minor edits to the draft.

**Comment by skmorgane** [comment]
This looks great. I made some minor edits. Looks good to submit to me.

**Comment by MarconiS** [comment]
looks good to me too. Awesome job!

**Comment by ethanwhite** [comment]
Thanks everyone!

@KristinaRiemer & @skmorgane - I've integrated your excellent comments and edits.

@KristinaRiemer - Are you happy for this to be submitted now?

Thanks @MarconiS!

@brymz - I've integrated your comments so far. Was that all of them or are you still working on things?

**Comment by KristinaRiemer** [comment]
@ethanwhite looks great! I definitely sign off on having it be submitted.

**Comment by brymz** [comment]
@ethanwhite: I just completed my review. 

The only idea I had that was not well served in the paper is a comment on the transcendent(?) structure of the course. We state that other instructors can repurpose the course design for other programming courses, but I think we could go further. The modular framework of the course can be agnostic to course customization and content. I used the course structure to develop a site focused on extension programming and structured workshops.  No strong feelings here. Just an idea.

Hi, everyone! All the best.

**Comment by andrewmarx** [comment]
@ethanwhite I've added the last of my comments/edits

**Comment by ethanwhite** [comment]
Thanks @andrewmarx & @brymz! I've got both of your comments integrated.

@brymz - I think that's a good point about the general infrastructure for the course. I added the following to the end of the "Course Infrastructure" section:

> This general infrastructure for modular, collaborative, and accessible course development is useful regardless of the content of the course. For example, one of the authors (Zachary Brym) uses the same infrastructure for teaching a [course on agroecology at the University of Florida](https://trec-agroecology.github.io/introducing-agroecology/). We hope that open courses on other topics can be built on this infrastructure to support the broader adoption of collaborative course development for college and university classrooms.

Thanks @KristinaRiemer!

**Comment by davharris** [comment]
Thanks everyone! I’ll still waive the option to review. 

Dave

**Comment by ethanwhite** [comment]
Just a quick update that we got very positive reviews at JOSE with only a few small changes requested for publication (fix some broken links, fix a bug that was trying to show solutions on documentation pages, and add some dependency information for local builds). I have done all of that (those of you following the repo will have seen this happening via issues over the last couple of months) and just let the JOSE editor know that these are done (https://github.com/openjournals/jose-reviews/issues/139#issuecomment-1005848404) along with shipping a new release with the changes (https://github.com/datacarpentry/semester-biology/releases/tag/v4.2.0).

Based on previous experiences with JOSS I expect that there may be a couple of small additional changes requested by the editor after some checks and then hopefully we'll be all done.

**Comment by ethanwhite** [comment]
We are now published at JOSE!!! https://doi.org/10.21105/jose.00139

Thanks again to everyone who has contributed to the course over the years and congratulations!

**Comment by MarconiS** [comment]
This is awesome! Congrats!
