### ISSUE TITLE
Instructor access request

### ISSUE THREAD

**Issue by Jpomz** [datacarpentry/semester-biology#942]
I am an instructor requesting access to the exercise solutions. This is in Response to Ethan White's response on Twitter. 

THANK YOU!
Justin

**Comment by ethanwhite** [comment]
Welcome @Jpomz! You should have just received an invite to the solutions repository. If you haven't let me know. If you've gotten access go ahead and close this issue.

**Comment by Jpomz** [comment]
Thanks @ethanwhite , looks like I have access now, I appreciate it!
